// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../../app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/submissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/submissions">> = Specific
  const handler = {} as typeof import("../../../app/admin/submissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analyze/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analyze">> = Specific
  const handler = {} as typeof import("../../../app/analyze/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/blend/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blend">> = Specific
  const handler = {} as typeof import("../../../app/blend/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare">> = Specific
  const handler = {} as typeof import("../../../app/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/components/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/components">> = Specific
  const handler = {} as typeof import("../../../app/components/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/create-style/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create-style">> = Specific
  const handler = {} as typeof import("../../../app/create-style/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/developers/api/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/developers/api">> = Specific
  const handler = {} as typeof import("../../../app/developers/api/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/developers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/developers">> = Specific
  const handler = {} as typeof import("../../../app/developers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../../app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/generate-style/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/generate-style">> = Specific
  const handler = {} as typeof import("../../../app/generate-style/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/generate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/generate">> = Specific
  const handler = {} as typeof import("../../../app/generate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide">> = Specific
  const handler = {} as typeof import("../../../app/guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/migrate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/migrate">> = Specific
  const handler = {} as typeof import("../../../app/migrate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline">> = Specific
  const handler = {} as typeof import("../../../app/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/playground/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playground">> = Specific
  const handler = {} as typeof import("../../../app/playground/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preview">> = Specific
  const handler = {} as typeof import("../../../app/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/styles/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/acid-graphics/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/acid-graphics/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/acid-graphics/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/anti-design/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/anti-design/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/anti-design/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/apple-style/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/apple-style/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/apple-style/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/arcade-crt/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/arcade-crt/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/arcade-crt/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/art-deco/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/art-deco/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/art-deco/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/art-nouveau/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/art-nouveau/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/art-nouveau/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/asymmetric-grid/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/asymmetric-grid/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/asymmetric-grid/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/bauhaus/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/bauhaus/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/bauhaus/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/bento-grid/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/bento-grid/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/bento-grid/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/card-stack/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/card-stack/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/card-stack/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/cel-shading/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/cel-shading/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/cel-shading/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/claymorphism/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/claymorphism/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/claymorphism/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/collage-art/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/collage-art/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/collage-art/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/comic-style/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/comic-style/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/comic-style/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/corporate-clean/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/corporate-clean/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/corporate-clean/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/cottagecore/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/cottagecore/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/cottagecore/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/cyber-anime/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/cyber-anime/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/cyber-anime/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/cyber-chinese/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/cyber-chinese/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/cyber-chinese/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/cyber-wafuu/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/cyber-wafuu/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/cyber-wafuu/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/cyberpunk-neon/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/cyberpunk-neon/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/cyberpunk-neon/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/dark-academia/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/dark-academia/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/dark-academia/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/dark-mode/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/dark-mode/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/dark-mode/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/dashboard-layout/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/dashboard-layout/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/dashboard-layout/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/editorial/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/editorial/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/editorial/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/f-pattern-layout/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/f-pattern-layout/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/f-pattern-layout/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/film-noir/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/film-noir/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/film-noir/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/fluent-design/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/fluent-design/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/fluent-design/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/frutiger-aero/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/frutiger-aero/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/frutiger-aero/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/full-page-scroll/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/full-page-scroll/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/full-page-scroll/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/generative-art/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/generative-art/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/generative-art/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/geometric-bold/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/geometric-bold/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/geometric-bold/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/ghibli-style/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/ghibli-style/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/ghibli-style/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/glassmorphism/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/glassmorphism/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/glassmorphism/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/glitch-art/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/glitch-art/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/glitch-art/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/gothic-lolita/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/gothic-lolita/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/gothic-lolita/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/gothic/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/gothic/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/gothic/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/hand-drawn-doodle/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/hand-drawn-doodle/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/hand-drawn-doodle/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/hero-fullscreen/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/hero-fullscreen/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/hero-fullscreen/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/holographic/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/holographic/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/holographic/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/holy-grail-layout/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/holy-grail-layout/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/holy-grail-layout/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/impressionist-oil/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/impressionist-oil/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/impressionist-oil/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/japanese-fresh/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/japanese-fresh/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/japanese-fresh/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/jrpg/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/jrpg/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/jrpg/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/kawaii-minimal/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/kawaii-minimal/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/kawaii-minimal/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/liquid-glass/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/liquid-glass/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/liquid-glass/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/magazine-grid/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/magazine-grid/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/magazine-grid/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/magic-circle/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/magic-circle/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/magic-circle/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/masonry-flow/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/masonry-flow/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/masonry-flow/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/material-design/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/material-design/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/material-design/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/mecha/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/mecha/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/mecha/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/memphis/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/memphis/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/memphis/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/minimalist-flat/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/minimalist-flat/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/minimalist-flat/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/modern-gradient/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/modern-gradient/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/modern-gradient/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/natural-organic/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/natural-organic/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/natural-organic/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/neo-brutalist-playful/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/neo-brutalist-playful/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/neo-brutalist-playful/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/neo-brutalist-soft/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/neo-brutalist-soft/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/neo-brutalist-soft/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/neo-brutalist/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/neo-brutalist/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/neo-brutalist/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/neon-gradient/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/neon-gradient/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/neon-gradient/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/neon-samurai/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/neon-samurai/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/neon-samurai/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/neumorphism/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/neumorphism/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/neumorphism/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/notion-style/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/notion-style/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/notion-style/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/outrun/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/outrun/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/outrun/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles">> = Specific
  const handler = {} as typeof import("../../../app/styles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/parallax-sections/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/parallax-sections/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/parallax-sections/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/particle/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/particle/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/particle/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/pixel-anime/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/pixel-anime/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/pixel-anime/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/pixel-art/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/pixel-art/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/pixel-art/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/pop-art/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/pop-art/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/pop-art/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/retro-vintage/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/retro-vintage/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/retro-vintage/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/risograph/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/risograph/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/risograph/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/scandinavian/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/scandinavian/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/scandinavian/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/sci-fi-hud/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/sci-fi-hud/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/sci-fi-hud/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/shoujo-manga/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/shoujo-manga/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/shoujo-manga/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/sidebar-fixed/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/sidebar-fixed/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/sidebar-fixed/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/sketch-style/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/sketch-style/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/sketch-style/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/skeuomorphism/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/skeuomorphism/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/skeuomorphism/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/soft-ui/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/soft-ui/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/soft-ui/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/solarpunk/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/solarpunk/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/solarpunk/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/split-screen/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/split-screen/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/split-screen/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/steampunk/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/steampunk/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/steampunk/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/stripe-style/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/stripe-style/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/stripe-style/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/surrealism/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/surrealism/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/surrealism/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/swiss-poster/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/swiss-poster/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/swiss-poster/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/swiss-style/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/swiss-style/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/swiss-style/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/synthwave/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/synthwave/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/synthwave/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/timeline-vertical/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/timeline-vertical/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/timeline-vertical/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/ukiyo-e-digital/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/ukiyo-e-digital/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/ukiyo-e-digital/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/vaporwave/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/vaporwave/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/vaporwave/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/vhs-aesthetic/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/vhs-aesthetic/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/vhs-aesthetic/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/visual-novel/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/visual-novel/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/visual-novel/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/wabi-sabi/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/wabi-sabi/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/wabi-sabi/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/warm-dashboard/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/warm-dashboard/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/warm-dashboard/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/watercolor-art/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/watercolor-art/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/watercolor-art/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/watercolor-style/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/watercolor-style/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/watercolor-style/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/y2k/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/y2k/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/y2k/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/styles/z-pattern-layout/showcase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/styles/z-pattern-layout/showcase">> = Specific
  const handler = {} as typeof import("../../../app/styles/z-pattern-layout/showcase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/submit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/submit">> = Specific
  const handler = {} as typeof import("../../../app/submit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/admin-panel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/admin-panel">> = Specific
  const handler = {} as typeof import("../../../app/templates/admin-panel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/anx-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/anx-blog">> = Specific
  const handler = {} as typeof import("../../../app/templates/anx-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/auth-pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/auth-pages">> = Specific
  const handler = {} as typeof import("../../../app/templates/auth-pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/blog-sidebar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/blog-sidebar">> = Specific
  const handler = {} as typeof import("../../../app/templates/blog-sidebar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/brutal-landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/brutal-landing">> = Specific
  const handler = {} as typeof import("../../../app/templates/brutal-landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/brutalist-playful-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/brutalist-playful-blog">> = Specific
  const handler = {} as typeof import("../../../app/templates/brutalist-playful-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/dashboard-charts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/dashboard-charts">> = Specific
  const handler = {} as typeof import("../../../app/templates/dashboard-charts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/docs-site/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/docs-site">> = Specific
  const handler = {} as typeof import("../../../app/templates/docs-site/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/ecommerce-product/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/ecommerce-product">> = Specific
  const handler = {} as typeof import("../../../app/templates/ecommerce-product/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/editorial-blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/editorial-blog">> = Specific
  const handler = {} as typeof import("../../../app/templates/editorial-blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/glass-landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/glass-landing">> = Specific
  const handler = {} as typeof import("../../../app/templates/glass-landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/magazine-landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/magazine-landing">> = Specific
  const handler = {} as typeof import("../../../app/templates/magazine-landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/minimalist-portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/minimalist-portfolio">> = Specific
  const handler = {} as typeof import("../../../app/templates/minimalist-portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/neumorphism-landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/neumorphism-landing">> = Specific
  const handler = {} as typeof import("../../../app/templates/neumorphism-landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates">> = Specific
  const handler = {} as typeof import("../../../app/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/portfolio-gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/portfolio-gallery">> = Specific
  const handler = {} as typeof import("../../../app/templates/portfolio-gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/pricing-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/pricing-page">> = Specific
  const handler = {} as typeof import("../../../app/templates/pricing-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/saas-landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/saas-landing">> = Specific
  const handler = {} as typeof import("../../../app/templates/saas-landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/settings-page/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/settings-page">> = Specific
  const handler = {} as typeof import("../../../app/templates/settings-page/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/startup-landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/startup-landing">> = Specific
  const handler = {} as typeof import("../../../app/templates/startup-landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/templates/warm-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates/warm-dashboard">> = Specific
  const handler = {} as typeof import("../../../app/templates/warm-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/accessibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/accessibility">> = Specific
  const handler = {} as typeof import("../../../app/api/accessibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/audit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/audit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analytics/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/api/analytics/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics">> = Specific
  const handler = {} as typeof import("../../../app/api/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analyze-style/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze-style">> = Specific
  const handler = {} as typeof import("../../../app/api/analyze-style/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/archetypes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/archetypes/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/archetypes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/archetypes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/archetypes">> = Specific
  const handler = {} as typeof import("../../../app/api/archetypes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/linuxdo/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/linuxdo/callback">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/linuxdo/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/linuxdo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/linuxdo">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/linuxdo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/favorites/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/favorites/merge">> = Specific
  const handler = {} as typeof import("../../../app/api/favorites/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/favorites">> = Specific
  const handler = {} as typeof import("../../../app/api/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/generate-style/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-style">> = Specific
  const handler = {} as typeof import("../../../app/api/generate-style/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/generate/design-system/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate/design-system">> = Specific
  const handler = {} as typeof import("../../../app/api/generate/design-system/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import-theme/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import-theme">> = Specific
  const handler = {} as typeof import("../../../app/api/import-theme/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/knowledge/domains/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/knowledge/domains">> = Specific
  const handler = {} as typeof import("../../../app/api/knowledge/domains/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/knowledge/recommend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/knowledge/recommend">> = Specific
  const handler = {} as typeof import("../../../app/api/knowledge/recommend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/knowledge/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/knowledge/search">> = Specific
  const handler = {} as typeof import("../../../app/api/knowledge/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/knowledge/smart/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/knowledge/smart">> = Specific
  const handler = {} as typeof import("../../../app/api/knowledge/smart/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/knowledge/stacks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/knowledge/stacks">> = Specific
  const handler = {} as typeof import("../../../app/api/knowledge/stacks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/lint/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lint">> = Specific
  const handler = {} as typeof import("../../../app/api/lint/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/match-style/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/match-style">> = Specific
  const handler = {} as typeof import("../../../app/api/match-style/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pipeline/run/[id]/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/run/[id]/retry">> = Specific
  const handler = {} as typeof import("../../../app/api/pipeline/run/[id]/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pipeline/run/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/run/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/pipeline/run/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pipeline/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pipeline/run">> = Specific
  const handler = {} as typeof import("../../../app/api/pipeline/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/profile/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/comments">> = Specific
  const handler = {} as typeof import("../../../app/api/profile/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/profile/ratings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/ratings">> = Specific
  const handler = {} as typeof import("../../../app/api/profile/ratings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/profile/submissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/submissions">> = Specific
  const handler = {} as typeof import("../../../app/api/profile/submissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/quality/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quality">> = Specific
  const handler = {} as typeof import("../../../app/api/quality/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/style-extract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/style-extract">> = Specific
  const handler = {} as typeof import("../../../app/api/style-extract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/styles/[slug]/claude-rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/styles/[slug]/claude-rules">> = Specific
  const handler = {} as typeof import("../../../app/api/styles/[slug]/claude-rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/styles/[slug]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/styles/[slug]/comments">> = Specific
  const handler = {} as typeof import("../../../app/api/styles/[slug]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/styles/[slug]/cursorrules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/styles/[slug]/cursorrules">> = Specific
  const handler = {} as typeof import("../../../app/api/styles/[slug]/cursorrules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/styles/[slug]/md/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/styles/[slug]/md">> = Specific
  const handler = {} as typeof import("../../../app/api/styles/[slug]/md/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/styles/[slug]/rate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/styles/[slug]/rate">> = Specific
  const handler = {} as typeof import("../../../app/api/styles/[slug]/rate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/styles/[slug]/recipes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/styles/[slug]/recipes">> = Specific
  const handler = {} as typeof import("../../../app/api/styles/[slug]/recipes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/styles/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/styles/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/api/styles/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/styles/[slug]/skill-pack/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/styles/[slug]/skill-pack">> = Specific
  const handler = {} as typeof import("../../../app/api/styles/[slug]/skill-pack/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/styles/[slug]/tokens/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/styles/[slug]/tokens">> = Specific
  const handler = {} as typeof import("../../../app/api/styles/[slug]/tokens/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/styles/[slug]/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/styles/[slug]/versions">> = Specific
  const handler = {} as typeof import("../../../app/api/styles/[slug]/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/styles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/styles">> = Specific
  const handler = {} as typeof import("../../../app/api/styles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/submit/[id]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submit/[id]/review">> = Specific
  const handler = {} as typeof import("../../../app/api/submit/[id]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/submit/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submit/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/submit/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/submit/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submit/list">> = Specific
  const handler = {} as typeof import("../../../app/api/submit/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submit">> = Specific
  const handler = {} as typeof import("../../../app/api/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ui-plan/schema/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ui-plan/schema">> = Specific
  const handler = {} as typeof import("../../../app/api/ui-plan/schema/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ui-plan/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ui-plan/validate">> = Specific
  const handler = {} as typeof import("../../../app/api/ui-plan/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/llms-full.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/llms-full.txt">> = Specific
  const handler = {} as typeof import("../../../app/llms-full.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/llms.md/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/llms.md">> = Specific
  const handler = {} as typeof import("../../../app/llms.md/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
