/**
 * Lightweight animation metadata module
 *
 * Contains ONLY metadata - no code snippets or heavy fields.
 * Import this in client components to avoid bundling full animation definitions.
 *
 * For full animation data (including codeSnippets), use:
 * import { getAnimationBySlug } from "@/lib/animations"
 */

import type { AnimationMeta } from "./types";

export const animationsMeta: AnimationMeta[] = [
  {
    slug: "fade-in-up",
    name: "淡入上滑",
    nameEn: "Fade In Up",
    description: "元素从下方淡入并向上滑动，最常见的入场动画之一。",
    category: "entrance",
    tags: ["fade", "slide", "entrance", "mount"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "600ms",
    keywords: ["fade in", "slide up", "entrance", "appear", "mount animation"],
  },
  {
    slug: "scale-in",
    name: "缩放淡入",
    nameEn: "Scale In",
    description: "元素从缩小状态放大至原始尺寸并淡入，适合卡片、弹窗等组件入场。",
    category: "entrance",
    tags: ["scale", "zoom", "entrance", "mount"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "400ms",
    keywords: ["scale", "zoom in", "entrance", "grow", "expand"],
  },
  {
    slug: "hover-lift",
    name: "悬浮抬升",
    nameEn: "Hover Lift",
    description: "鼠标悬停时元素向上移动并加深阴影，营造悬浮立体感。",
    category: "hover",
    tags: ["hover", "lift", "shadow", "interactive"],
    trigger: "on-hover",
    difficulty: "beginner",
    duration: "200ms",
    keywords: ["hover", "lift", "float", "shadow", "card hover", "elevation"],
  },
  {
    slug: "typewriter",
    name: "打字机效果",
    nameEn: "Typewriter",
    description: "文字逐字显现并带有闪烁光标，模拟打字机输入效果。",
    category: "text",
    tags: ["text", "typewriter", "cursor", "sequential"],
    trigger: "on-mount",
    difficulty: "intermediate",
    duration: "3s",
    keywords: ["typewriter", "typing", "text reveal", "cursor blink", "sequential text"],
  },
  {
    slug: "skeleton-pulse",
    name: "骨架屏脉冲",
    nameEn: "Skeleton Pulse",
    description: "骨架屏加载占位符的脉冲闪烁效果，提示用户内容正在加载中。",
    category: "loading",
    tags: ["loading", "skeleton", "pulse", "placeholder"],
    trigger: "continuous",
    difficulty: "beginner",
    duration: "2s",
    keywords: ["skeleton", "loading", "pulse", "shimmer", "placeholder", "content loading"],
  },
  {
    slug: "fade-in-down",
    name: "淡入下滑",
    nameEn: "Fade In Down",
    description: "元素从上方淡入并向下滑动，常用于导航栏、下拉菜单入场。",
    category: "entrance",
    tags: ["fade", "slide", "entrance", "dropdown"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "600ms",
    keywords: ["fade in", "slide down", "entrance", "dropdown", "navbar"],
  },
  {
    slug: "slide-in-left",
    name: "左侧滑入",
    nameEn: "Slide In Left",
    description: "元素从左侧滑入视口，适合侧边栏、抽屉菜单等组件。",
    category: "entrance",
    tags: ["slide", "entrance", "horizontal", "sidebar"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "500ms",
    keywords: ["slide", "left", "entrance", "sidebar", "drawer", "panel"],
  },
  {
    slug: "hover-glow",
    name: "悬浮发光",
    nameEn: "Hover Glow",
    description: "鼠标悬停时元素边框发出柔和光晕，适合 CTA 按钮和交互卡片。",
    category: "hover",
    tags: ["hover", "glow", "border", "interactive"],
    trigger: "on-hover",
    difficulty: "beginner",
    duration: "300ms",
    keywords: ["hover", "glow", "border glow", "neon", "CTA", "button hover"],
  },
  {
    slug: "scroll-reveal",
    name: "滚动显现",
    nameEn: "Scroll Reveal",
    description: "元素进入视口时淡入显现，利用 IntersectionObserver 实现滚动触发。",
    category: "scroll",
    tags: ["scroll", "reveal", "intersection", "viewport"],
    trigger: "on-scroll",
    difficulty: "intermediate",
    duration: "600ms",
    keywords: ["scroll", "reveal", "viewport", "intersection observer", "lazy", "on-scroll"],
  },
  {
    slug: "parallax-float",
    name: "视差浮动",
    nameEn: "Parallax Float",
    description: "元素随滚动以不同速率移动，产生深度视差效果，增强页面层次感。",
    category: "scroll",
    tags: ["scroll", "parallax", "depth", "float"],
    trigger: "on-scroll",
    difficulty: "intermediate",
    duration: "continuous",
    keywords: ["parallax", "float", "depth", "scroll speed", "layers", "3D"],
  },
  {
    slug: "text-gradient-flow",
    name: "文字渐变流动",
    nameEn: "Text Gradient Flow",
    description: "文字颜色以渐变方式持续流动变化，吸引注意力的标题效果。",
    category: "text",
    tags: ["text", "gradient", "flow", "color", "continuous"],
    trigger: "continuous",
    difficulty: "beginner",
    duration: "3s",
    keywords: ["text gradient", "gradient flow", "animated text", "color shift", "headline"],
  },
  {
    slug: "spinner-dots",
    name: "三点弹跳加载",
    nameEn: "Spinner Dots",
    description: "三个圆点依次弹跳的加载指示器，轻量且易于实现。",
    category: "loading",
    tags: ["loading", "spinner", "dots", "bounce"],
    trigger: "continuous",
    difficulty: "beginner",
    duration: "1.4s",
    keywords: ["spinner", "dots", "loading", "bounce", "indicator", "three dots"],
  },
  {
    slug: "background-gradient-shift",
    name: "背景渐变流动",
    nameEn: "Background Gradient Shift",
    description: "背景渐变颜色持续缓慢流动变化，营造动态氛围感。",
    category: "background",
    tags: ["background", "gradient", "ambient", "continuous"],
    trigger: "continuous",
    difficulty: "beginner",
    duration: "8s",
    keywords: ["background", "gradient", "shift", "ambient", "flow", "color change"],
  },
  {
    slug: "stagger-children",
    name: "子元素错开动画",
    nameEn: "Stagger Children",
    description: "子元素依次错开执行入场动画，通过延迟差营造流畅的序列感。",
    category: "micro-interaction",
    tags: ["stagger", "sequence", "children", "cascade", "list"],
    trigger: "on-mount",
    difficulty: "intermediate",
    duration: "500ms",
    keywords: ["stagger", "cascade", "sequence", "children", "list animation", "delay"],
  },
  {
    slug: "blur-in",
    name: "模糊到清晰",
    nameEn: "Blur In",
    description: "元素从模糊状态逐渐变清晰并淡入，营造柔和的过渡入场效果。",
    category: "transition",
    tags: ["blur", "focus", "entrance", "transition"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "500ms",
    keywords: ["blur", "focus", "sharp", "entrance", "transition", "soft"],
  },
  {
    slug: "spotlight-card",
    name: "聚光灯卡片",
    nameEn: "Spotlight Card",
    description: "鼠标在卡片上方移动时，呈现手电筒照亮卡片局部的光影跟随效果。",
    category: "micro-interaction",
    tags: ["hover", "spotlight", "glow", "mouse-tracking"],
    trigger: "on-hover",
    difficulty: "advanced",
    duration: "continuous",
    keywords: ["spotlight", "mouse tracking", "glow", "card effect", "lighting"],
  },
  {
    slug: "magnetic-hover",
    name: "磁吸悬浮",
    nameEn: "Magnetic Hover",
    description: "鼠标靠近目标元素时，元素会像被磁铁吸引一样向鼠标指针方向产生弹性位移。",
    category: "micro-interaction",
    tags: ["hover", "magnetic", "physics", "interactive"],
    trigger: "on-hover",
    difficulty: "intermediate",
    duration: "continuous",
    keywords: ["magnetic", "spring", "button hover", "physics", "attract"],
  },
  {
    slug: "bounce-in",
    name: "弹性入场",
    nameEn: "Bounce In",
    description: "元素以弹性缩放方式入场，从小尺寸弹跳过冲后稳定在原始大小，充满活力感。",
    category: "entrance",
    tags: ["bounce", "scale", "entrance", "elastic", "mount"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "600ms",
    keywords: ["bounce", "elastic", "spring", "entrance", "scale", "overshoot"],
  },
  {
    slug: "slide-in-right",
    name: "右侧滑入",
    nameEn: "Slide In Right",
    description: "元素从右侧滑入视口，适合侧面板、抽屉菜单和分屏布局的入场效果。",
    category: "entrance",
    tags: ["slide", "entrance", "horizontal", "panel"],
    trigger: "on-mount",
    difficulty: "beginner",
    duration: "500ms",
    keywords: ["slide", "right", "entrance", "panel", "drawer", "horizontal"],
  },
  {
    slug: "rotate-in",
    name: "旋转入场",
    nameEn: "Rotate In",
    description: "元素从反向旋转并透明的状态旋转至正位并淡入，适合图标和趣味性入场。",
    category: "entrance",
    tags: ["rotate", "spin", "entrance", "mount"],
    trigger: "on-mount",
    difficulty: "intermediate",
    duration: "500ms",
    keywords: ["rotate", "spin", "entrance", "turn", "twist", "icon animation"],
  },
  {
    slug: "shake",
    name: "抖动提示",
    nameEn: "Shake",
    description: "元素在水平方向快速抖动，常用于表单校验失败或错误提示的视觉反馈。",
    category: "micro-interaction",
    tags: ["shake", "error", "feedback", "attention", "click"],
    trigger: "on-click",
    difficulty: "beginner",
    duration: "500ms",
    keywords: ["shake", "vibrate", "error", "validation", "feedback", "attention"],
  },
  {
    slug: "flip-card",
    name: "3D 卡片翻转",
    nameEn: "Flip Card",
    description: "卡片沿 Y 轴进行 3D 翻转，显示背面内容，需要透视容器和 backface-visibility 控制。",
    category: "hover",
    tags: ["flip", "3d", "card", "hover", "perspective"],
    trigger: "on-hover",
    difficulty: "advanced",
    duration: "600ms",
    keywords: ["flip", "card", "3d", "rotate", "perspective", "backface", "two-sided"],
  },
  {
    slug: "ripple-click",
    name: "涟漪点击",
    nameEn: "Ripple Click",
    description: "点击时从触发点产生向外扩散的圆形涟漪效果，Material Design 风格的经典交互反馈。",
    category: "micro-interaction",
    tags: ["ripple", "click", "material", "feedback", "interactive"],
    trigger: "on-click",
    difficulty: "intermediate",
    duration: "600ms",
    keywords: ["ripple", "click", "material design", "wave", "touch feedback", "button click"],
  },
  {
    slug: "counter-roll",
    name: "数字滚动",
    nameEn: "Counter Roll",
    description: "数字通过垂直滚动方式从 0 滚动至目标值，适合数据面板和统计展示。",
    category: "text",
    tags: ["counter", "number", "scroll", "data", "stats"],
    trigger: "on-scroll",
    difficulty: "intermediate",
    duration: "2s",
    keywords: ["counter", "number", "roll", "count up", "statistics", "dashboard"],
  },
  {
    slug: "morph-shape",
    name: "形状变形",
    nameEn: "Morph Shape",
    description: "通过 border-radius 过渡实现有机的 blob 形状连续变形，适合装饰性背景元素。",
    category: "background",
    tags: ["morph", "blob", "organic", "background", "continuous"],
    trigger: "continuous",
    difficulty: "advanced",
    duration: "8s",
    keywords: ["morph", "blob", "shape", "organic", "border-radius", "ambient", "background"],
  },
];

export function getAllAnimationsMeta(): AnimationMeta[] {
  return animationsMeta;
}

export function getAnimationMetaBySlug(slug: string): AnimationMeta | undefined {
  return animationsMeta.find((a) => a.slug === slug);
}
