/**
 * Bundle the service to a single self-contained dist/server.mjs.
 *
 * The converter (lib/submit/extract-to-manifest) and the SSRF guard are bundled
 * in so the deployed host needs only Node, playwright-core, the extractor
 * scripts, and a Chrome binary — not a checkout of the main repo. playwright-core
 * stays external (it has a native/runtime component that must be npm-installed).
 */

import { build } from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..", "..");

await build({
  entryPoints: [path.join(here, "src", "server.ts")],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  outfile: path.join(here, "dist", "server.mjs"),
  external: ["playwright-core"],
  // Resolve the main repo's `@/` alias so the shared converter bundles in.
  alias: { "@": repoRoot },
  banner: {
    js: "// Generated by services/style-extract/build.mjs — do not edit dist/ by hand.",
  },
  logLevel: "info",
});

process.stdout.write("[build] wrote dist/server.mjs\n");
