/**
 * Lightweight style metadata module
 *
 * This module contains ONLY metadata - no component templates, CSS, or AI rules.
 * Import this in client components to avoid bundling the full style definitions.
 *
 * For full style data (including components, globalCss, aiRules), use:
 * import { getStyleBySlug } from "@/lib/styles"
 */

// Type definitions (duplicated to avoid importing from index.ts)
export type StyleCategory = "modern" | "retro" | "minimal" | "expressive";
export type StyleType = "visual" | "layout" | "animation";
export type StyleTag =
  | "modern"
  | "retro"
  | "minimal"
  | "expressive"
  | "high-contrast"
  | "responsive"
  | "brand-inspired";

export interface StyleMeta {
  slug: string;
  name: string;
  nameEn: string;
  description: string;
  cover: string;
  category: StyleCategory;
  styleType: StyleType;
  tags: StyleTag[];
  compatibleWith?: string[];
  keywords: string[];
  colors: {
    primary: string;
    secondary: string;
    accent: string[];
  };
}

/**
 * Static metadata for all styles
 * Extracted from individual style files to avoid bundling full definitions
 */
export const stylesMeta: StyleMeta[] = [
  {
    slug: "neo-brutalist",
    name: "新野兽派",
    nameEn: "Neo-Brutalist",
    description: "大胆的黑色粗边框、硬边缘阴影、无圆角、高对比度配色。源于建筑野兽派，强调功能与原始美学。包含经典、柔和、俏皮三种变体。",
    cover: "/styles/neo-brutalist.png",
    styleType: "visual",
    tags: ["expressive", "high-contrast"],
    category: "expressive",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff006e", "#ccff00", "#00d9ff", "#ff9500"],
    },
    keywords: ["粗边框", "硬阴影", "无圆角", "高对比", "功能主义", "柔和野兽派", "俏皮野兽派"],
  },
  {
    slug: "editorial",
    name: "编辑杂志风",
    nameEn: "Editorial",
    description: "优雅的杂志排版风格，衬线标题、无衬线正文、精致的留白和网格系统。灵感来自高端时尚杂志和报纸排版。",
    cover: "/styles/editorial.png",
    styleType: "visual",
    tags: ["minimal"],
    category: "minimal",
    colors: {
      primary: "#0a0a0a",
      secondary: "#fafafa",
      accent: ["#e63946", "#6b7280", "#e5e5e5"],
    },
    keywords: ["杂志排版", "衬线字体", "优雅留白", "网格系统", "极简主义"],
  },
  {
    slug: "neumorphism",
    name: "新拟物派",
    nameEn: "Neumorphism",
    description: "柔和的内凹外凸立体效果，通过双重阴影模拟光源，浅色背景配同色系元素，营造精致的立体感。",
    cover: "/styles/neumorphism.png",
    styleType: "visual",
    tags: ["modern", "minimal"],
    category: "modern",
    colors: {
      primary: "#e0e5ec",
      secondary: "#d1d9e6",
      accent: ["#6d5dfc", "#ff6b6b", "#4ecdc4", "#ffe66d"],
    },
    keywords: ["立体感", "双重阴影", "柔和", "浅色系", "内凹外凸"],
  },
  {
    slug: "glassmorphism",
    name: "玻璃拟态",
    nameEn: "Glassmorphism",
    description: "半透明毛玻璃效果，通过 backdrop-blur 模糊背景、柔和边框和微妙阴影，创造现代感十足的层叠界面。",
    cover: "/styles/glassmorphism.png",
    styleType: "visual",
    tags: ["modern"],
    category: "modern",
    colors: {
      primary: "rgba(255, 255, 255, 0.25)",
      secondary: "rgba(255, 255, 255, 0.18)",
      accent: ["#667eea", "#764ba2", "#f093fb", "#f5576c"],
    },
    keywords: ["毛玻璃", "透明", "模糊", "现代", "层叠"],
  },
  {
    slug: "bento-grid",
    name: "便当盒布局",
    nameEn: "Bento Grid",
    description: "灵感源于日式便当盒的不规则网格布局，通过大小不一的卡片组合创造视觉层次，常用于作品集和产品展示。",
    cover: "/styles/bento-grid.png",
    styleType: "layout",
    tags: ["modern", "responsive"],
    category: "modern",
    colors: {
      primary: "#18181b",
      secondary: "#fafafa",
      accent: ["#3b82f6", "#8b5cf6", "#ec4899", "#f97316"],
    },
    keywords: ["网格", "卡片", "不规则", "作品集", "现代"],
    compatibleWith: ["glassmorphism", "neo-brutalist", "editorial", "neumorphism"],
  },
  {
    slug: "corporate-clean",
    name: "企业简洁风",
    nameEn: "Corporate Clean",
    description: "专业简洁的企业风格，强调可读性、一致性和信任感。适合B2B SaaS、企业官网、后台管理系统。",
    cover: "/styles/corporate-clean.png",
    styleType: "visual",
    tags: ["minimal", "modern"],
    category: "minimal",
    colors: {
      primary: "#1e40af",
      secondary: "#f8fafc",
      accent: ["#3b82f6", "#64748b", "#10b981"],
    },
    keywords: ["企业", "专业", "简洁", "B2B", "SaaS", "后台", "Dashboard"],
  },
  {
    slug: "minimalist-flat",
    name: "极简扁平风",
    nameEn: "Minimalist Flat",
    description: "极致简约的扁平设计，无阴影无渐变，通过颜色和留白创造层次。适合作品集、创意机构、艺术网站。",
    cover: "/styles/minimalist-flat.png",
    styleType: "visual",
    tags: ["minimal", "modern"],
    category: "minimal",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff3366", "#00d4aa", "#ffcc00"],
    },
    keywords: ["极简", "扁平", "无阴影", "作品集", "创意", "艺术"],
  },
  {
    slug: "soft-ui",
    name: "柔和界面风",
    nameEn: "Soft UI",
    description: "温���友好的界面风格，柔和的阴影、圆润的边角、低饱和度的配色。适合消费类应用、社交产品、生活服务类 App。",
    cover: "/styles/soft-ui.png",
    styleType: "visual",
    tags: ["modern", "minimal"],
    category: "modern",
    colors: {
      primary: "#6366f1",
      secondary: "#f1f5f9",
      accent: ["#ec4899", "#10b981", "#f59e0b"],
    },
    keywords: ["柔和", "圆润", "友好", "消费类", "App", "社交", "生活服务"],
  },
  {
    slug: "natural-organic",
    name: "自然有机风",
    nameEn: "Natural Organic",
    description: "温暖自然的有机风格，大地色系、自然纹理、手工感元素。适合健康品牌、有机食品、环保产品、手工艺品。",
    cover: "/styles/natural-organic.png",
    styleType: "visual",
    tags: ["minimal", "modern"],
    category: "minimal",
    colors: {
      primary: "#5c4033",
      secondary: "#faf6f1",
      accent: ["#8b9d77", "#d4a373", "#e9e0d4"],
    },
    keywords: ["自然", "有机", "大地色", "手工", "健康", "环保", "可持续"],
  },
  {
    slug: "modern-gradient",
    name: "现代渐变风",
    nameEn: "Modern Gradient",
    description: "充满活力的现代渐变风格，多彩渐变背景、玻璃�����感卡片、动态光影效果。适合创业公司、数字产品、活动页面。",
    cover: "/styles/modern-gradient.png",
    styleType: "visual",
    tags: ["expressive", "modern"],
    category: "expressive",
    colors: {
      primary: "#8b5cf6",
      secondary: "#1e1b4b",
      accent: ["#06b6d4", "#ec4899", "#f59e0b"],
    },
    keywords: ["渐变", "现代", "活力", "创业", "数字", "动态", "科技感"],
  },
  {
    slug: "retro-vintage",
    name: "复古怀旧风",
    nameEn: "Retro Vintage",
    description: "怀旧复古的设计风格，老式排版、复古色调、手工质感元素。适合咖啡馆、复古品牌、独立杂志、音乐厂牌。",
    cover: "/styles/retro-vintage.png",
    styleType: "visual",
    tags: ["retro", "expressive"],
    category: "retro",
    colors: {
      primary: "#8b4513",
      secondary: "#f5e6d3",
      accent: ["#c94c4c", "#2e4a3f", "#d4a373"],
    },
    keywords: ["复古", "怀旧", "老式", "手工", "咖啡馆", "独立", "文艺"],
  },
  {
    slug: "dark-mode",
    name: "暗黑模式",
    nameEn: "Dark Mode",
    description: "优雅的深色界面设计，低对比度层次、微妙的边框和高亮。适合开发工具、专业应用、深夜阅读模式。",
    cover: "/styles/dark-mode.png",
    styleType: "visual",
    tags: ["modern", "minimal"],
    category: "modern",
    colors: {
      primary: "#3b82f6",
      secondary: "#0f172a",
      accent: ["#22c55e", "#f59e0b", "#ef4444"],
    },
    keywords: ["暗黑", "深色", "夜间", "开发", "专业", "护眼"],
  },
  {
    slug: "geometric-bold",
    name: "几何大胆风",
    nameEn: "Geometric Bold",
    description: "大胆的几何图形设计，强烈的形状对比、鲜明的色块、动态的构图。适合艺术展览、设计机构、创意品牌。",
    cover: "/styles/geometric-bold.png",
    styleType: "visual",
    tags: ["expressive", "high-contrast"],
    category: "expressive",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff0000", "#0000ff", "#ffff00"],
    },
    keywords: ["几何", "大胆", "色块", "艺术", "创意", "设计", "先锋"],
  },
  // 新增布局风格
  {
    slug: "masonry-flow",
    name: "瀑布流布局",
    nameEn: "Masonry Flow",
    description: "Pinterest 风格的不等高卡片瀑布流布局，通过 CSS columns 或 masonry grid 实现自然流动的视觉效果，适合图片展示、作品集、社交媒体。",
    cover: "/styles/masonry-flow.png",
    styleType: "layout",
    tags: ["modern", "responsive"],
    category: "modern",
    colors: {
      primary: "#1a1a2e",
      secondary: "#f5f5f5",
      accent: ["#e94560", "#16c79a", "#ffd460", "#7579e7"],
    },
    keywords: ["瀑布流", "Pinterest", "不等高", "图片墙", "作品集", "gallery"],
    compatibleWith: ["glassmorphism", "minimalist-flat", "soft-ui", "natural-organic", "editorial"],
  },
  {
    slug: "split-screen",
    name: "分屏布局",
    nameEn: "Split Screen",
    description: "左右对称或不对称的分屏布局，通过对比和平衡创造视觉张力，常用于产品展示、品牌故事、比较页面。",
    cover: "/styles/split-screen.png",
    styleType: "layout",
    tags: ["modern", "responsive"],
    category: "modern",
    colors: {
      primary: "#0f0f0f",
      secondary: "#ffffff",
      accent: ["#ff4757", "#2ed573", "#1e90ff", "#ffa502"],
    },
    keywords: ["分屏", "对比", "左右布局", "对称", "品牌", "展示"],
    compatibleWith: ["neo-brutalist", "minimalist-flat", "editorial", "modern-gradient", "geometric-bold"],
  },
  {
    slug: "full-page-scroll",
    name: "全屏滚动布局",
    nameEn: "Full Page Scroll",
    description: "每一屏占满整个视口的沉浸式滚动体验，通过滚动切换完整场景，适合��牌故事、产品��绍、作品集展示。",
    cover: "/styles/full-page-scroll.png",
    styleType: "layout",
    tags: ["modern", "expressive"],
    category: "expressive",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#6366f1", "#ec4899", "#14b8a6", "#f59e0b"],
    },
    keywords: ["全屏", "滚动", "沉浸式", "场景", "品牌", "故事"],
    compatibleWith: ["glassmorphism", "modern-gradient", "cyberpunk-neon", "minimalist-flat", "geometric-bold"],
  },
  {
    slug: "timeline-vertical",
    name: "垂直时间线布局",
    nameEn: "Vertical Timeline",
    description: "垂直时间轴布局，通过连接线串联时间节点，适合展示历史进程、项目里程碑、工作经历、流程步骤。",
    cover: "/styles/timeline-vertical.png",
    styleType: "layout",
    tags: ["modern", "minimal"],
    category: "minimal",
    colors: {
      primary: "#1e293b",
      secondary: "#f8fafc",
      accent: ["#3b82f6", "#10b981", "#f59e0b", "#ef4444"],
    },
    keywords: ["时间线", "历程", "里程碑", "流程", "步骤", "进度"],
    compatibleWith: ["editorial", "corporate-clean", "minimalist-flat", "soft-ui", "natural-organic"],
  },
  {
    slug: "card-stack",
    name: "卡片堆叠布局",
    nameEn: "Card Stack",
    description: "卡片前后重叠的立体布局，通过 Z 轴层叠和偏移创造深度感，适合轮播、步骤展示、卡组选择。",
    cover: "/styles/card-stack.png",
    styleType: "layout",
    tags: ["modern", "expressive"],
    category: "expressive",
    colors: {
      primary: "#1a1a2e",
      secondary: "#f0f0f5",
      accent: ["#6c5ce7", "#00cec9", "#fd79a8", "#ffeaa7"],
    },
    keywords: ["卡片", "堆叠", "立体", "层叠", "轮播", "3D"],
    compatibleWith: ["glassmorphism", "neumorphism", "soft-ui", "modern-gradient", "neo-brutalist"],
  },
  {
    slug: "sidebar-fixed",
    name: "固定侧边栏布局",
    nameEn: "Fixed Sidebar",
    description: "固定位置的侧边导航栏与可滚动主内容区的应用布局，适合后台管理、文档站点、仪表盘、SaaS 应用。",
    cover: "/styles/sidebar-fixed.png",
    styleType: "layout",
    tags: ["modern", "responsive"],
    category: "modern",
    colors: {
      primary: "#1e293b",
      secondary: "#f8fafc",
      accent: ["#3b82f6", "#10b981", "#f59e0b", "#ef4444"],
    },
    keywords: ["侧边栏", "后台", "管理", "导航", "仪表盘", "应用"],
    compatibleWith: ["corporate-clean", "soft-ui", "dark-mode", "minimalist-flat", "neumorphism"],
  },
  {
    slug: "magazine-grid",
    name: "杂志网格布局",
    nameEn: "Magazine Grid",
    description: "灵感来自印刷杂志的多栏网格布局，通过不同大小的内容块创造丰富的视觉层次，适合新闻、博客、内容聚合。",
    cover: "/styles/magazine-grid.png",
    styleType: "layout",
    tags: ["modern", "responsive"],
    category: "modern",
    colors: {
      primary: "#1a1a1a",
      secondary: "#fafafa",
      accent: ["#e63946", "#2a9d8f", "#e9c46a", "#264653"],
    },
    keywords: ["杂志", "多栏", "新闻", "博客", "内容", "网格"],
    compatibleWith: ["editorial", "minimalist-flat", "corporate-clean", "retro-vintage", "dark-mode"],
  },
  {
    slug: "hero-fullscreen",
    name: "全屏英雄区布局",
    nameEn: "Fullscreen Hero",
    description: "以全屏大图或视频为背景的英雄区布局，通过震撼的视觉效果抓住注意力，适合品牌展示、产品发布、活动宣传。",
    cover: "/styles/hero-fullscreen.png",
    styleType: "layout",
    tags: ["expressive", "modern"],
    category: "expressive",
    colors: {
      primary: "#ffffff",
      secondary: "#000000",
      accent: ["#ff6b6b", "#4ecdc4", "#ffe66d", "#6c5ce7"],
    },
    keywords: ["全屏", "英雄区", "大图", "视频", "品牌", "震撼"],
    compatibleWith: ["glassmorphism", "modern-gradient", "cyberpunk-neon", "minimalist-flat", "dark-mode"],
  },
  // 新增视觉风格
  {
    slug: "claymorphism",
    name: "粘土拟态",
    nameEn: "Claymorphism",
    description: "柔软的粘土质感设计，通过超大圆角、内外阴影组合和柔和渐变，创造出可爱的 3D 立体效果，适合儿童应用和趣味产品。",
    cover: "/styles/claymorphism.svg",
    styleType: "visual",
    tags: ["modern", "expressive"],
    category: "modern",
    colors: {
      primary: "#f8b4d9",
      secondary: "#fef3c7",
      accent: ["#a7f3d0", "#c4b5fd", "#fcd34d"],
    },
    keywords: ["粘土", "3D", "可爱", "柔软", "圆润", "儿童", "趣味"],
  },
  {
    slug: "notion-style",
    name: "Notion 风格",
    nameEn: "Notion Style",
    description: "极简清爽的文档工具风格，强调内容可读性和功能性，使用微妙的边框、柔和的悬停效果和清晰的文字层级。",
    cover: "/styles/notion-style.svg",
    styleType: "visual",
    tags: ["minimal", "brand-inspired"],
    category: "minimal",
    colors: {
      primary: "#37352f",
      secondary: "#ffffff",
      accent: ["#2eaadc", "#eb5757", "#0f7b6c"],
    },
    keywords: ["Notion", "文档", "极简", "清爽", "工具", "协作", "笔记"],
  },
  {
    slug: "stripe-style",
    name: "Stripe 风格",
    nameEn: "Stripe Style",
    description: "精致专业的金融科技风格，以 Stripe 紫为主色调，配合渐变网格背景、精致卡片阴影和流畅动画，适合支付产品和开发者工具。",
    cover: "/styles/stripe-style.svg",
    styleType: "visual",
    tags: ["modern", "brand-inspired"],
    category: "modern",
    colors: {
      primary: "#635bff",
      secondary: "#0a2540",
      accent: ["#00d4ff", "#7a73ff", "#80e9ff"],
    },
    keywords: ["Stripe", "金融", "支付", "SaaS", "开发者", "专业", "科技"],
  },
  {
    slug: "apple-style",
    name: "Apple 风格",
    nameEn: "Apple Style",
    description: "极致简约的高端设计风格，大量留白、精致圆角、微妙阴影和 SF Pro 风格字体，传达高端科技产品的品质感。",
    cover: "/styles/apple-style.svg",
    styleType: "visual",
    tags: ["minimal", "brand-inspired"],
    category: "minimal",
    colors: {
      primary: "#000000",
      secondary: "#f5f5f7",
      accent: ["#0071e3", "#34c759", "#ff3b30"],
    },
    keywords: ["Apple", "极简", "高端", "科技", "产品", "留白", "精致"],
  },
  {
    slug: "pixel-art",
    name: "像素艺术风",
    nameEn: "Pixel Art",
    description: "复古 8-bit 像素游戏风格，无圆角、像素化边框、硬边阴影和鲜明的 8-bit 配色，适合游戏、复古应用和独立开发者项目。",
    cover: "/styles/pixel-art.svg",
    styleType: "visual",
    tags: ["retro", "expressive"],
    category: "retro",
    colors: {
      primary: "#1a1c2c",
      secondary: "#f4f4f4",
      accent: ["#ff004d", "#00e436", "#29adff", "#ffec27"],
    },
    keywords: ["像素", "8-bit", "复古", "游戏", "怀旧", "独立", "retro"],
  },
  // 新增风格 - 批次1
  {
    slug: "vaporwave",
    name: "霓虹复古",
    nameEn: "Neon Retro",
    description: "80-90年代复古未来主义美学，粉紫渐变、霓虹色彩、故障艺术效果。包含蒸汽波、合成波、赛博朋克三种变体。",
    cover: "/styles/vaporwave.svg",
    styleType: "visual",
    tags: ["retro", "expressive", "high-contrast"],
    category: "retro",
    colors: {
      primary: "#ff71ce",
      secondary: "#01cdfe",
      accent: ["#05ffa1", "#b967ff", "#fffb96"],
    },
    keywords: ["蒸汽波", "复古未来", "霓虹", "80年代", "故障艺术", "赛博", "合成波", "赛博朋克", "vaporwave", "synthwave", "cyberpunk"],
  },
  {
    slug: "y2k",
    name: "千禧风格",
    nameEn: "Y2K",
    description: "2000年代初的未来主义美学，金属质感、透明塑料、气泡元素、银色和彩虹渐变。",
    cover: "/styles/y2k.svg",
    styleType: "visual",
    tags: ["retro", "expressive"],
    category: "retro",
    colors: {
      primary: "#c0c0c0",
      secondary: "#ff69b4",
      accent: ["#00ffff", "#ff00ff", "#87ceeb"],
    },
    keywords: ["Y2K", "千禧", "未来主义", "金属", "透明", "气泡", "2000年代"],
  },
  {
    slug: "memphis",
    name: "孟菲斯风格",
    nameEn: "Memphis",
    description: "80年代意大利设计运动，大胆的几何图形、鲜艳的撞色、不规则形状和有趣的图案。",
    cover: "/styles/memphis.svg",
    styleType: "visual",
    tags: ["retro", "expressive", "high-contrast"],
    category: "retro",
    colors: {
      primary: "#ff6b6b",
      secondary: "#feca57",
      accent: ["#48dbfb", "#ff9ff3", "#1dd1a1", "#5f27cd"],
    },
    keywords: ["孟菲斯", "几何", "撞色", "80年代", "波普", "图案", "大胆"],
  },
  {
    slug: "art-deco",
    name: "装饰艺术风格",
    nameEn: "Art Deco",
    description: "1920-30年代的奢华设计风格，几何对称图案、金色装饰、优雅线条和高端质感。",
    cover: "/styles/art-deco.svg",
    styleType: "visual",
    tags: ["retro", "expressive"],
    category: "retro",
    colors: {
      primary: "#d4af37",
      secondary: "#1a1a2e",
      accent: ["#c9a227", "#2d2d44", "#f5f5dc"],
    },
    keywords: ["装饰艺术", "奢华", "金色", "几何", "1920年代", "优雅", "高端"],
  },
  {
    slug: "bauhaus",
    name: "���豪斯风格",
    nameEn: "Bauhaus",
    description: "德国包豪斯学派的设计理念，强调功能主义、几何形式和原色运用，形式追随功能。",
    cover: "/styles/bauhaus.svg",
    styleType: "visual",
    tags: ["modern", "minimal", "high-contrast"],
    category: "modern",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff0000", "#ffcc00", "#0000ff"],
    },
    keywords: ["包豪斯", "功能主义", "几何", "原色", "现代主义", "极简"],
  },
  // 新增风格 - 批次2
  {
    slug: "skeuomorphism",
    name: "拟物设计",
    nameEn: "Skeuomorphism",
    description: "模拟真实世界物体的数字设计风格，通过纹理、光影、材质模仿现实物品，带来熟悉感和直觉性体验。",
    cover: "/styles/skeuomorphism.svg",
    styleType: "visual",
    tags: ["retro", "expressive"],
    category: "retro",
    colors: {
      primary: "#8b7355",
      secondary: "#d4c4a8",
      accent: ["#c9a227", "#5c4033", "#2e5a3c"],
    },
    keywords: ["拟物", "写实", "纹理", "质感", "真实", "3D", "阴影"],
  },
  {
    slug: "swiss-style",
    name: "瑞士国际风格",
    nameEn: "Swiss International",
    description: "源于瑞士的理性主义设计风格，强调网格系统、无衬线字体、清晰层次和客观信息传达，是现代平面设计的基石。",
    cover: "/styles/swiss-style.svg",
    styleType: "visual",
    tags: ["modern", "minimal"],
    category: "modern",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff0000", "#0057b8", "#ffcc00"],
    },
    keywords: ["瑞士", "国际主义", "网格", "Helvetica", "理性", "排版", "极简"],
  },
  {
    slug: "ghibli-style",
    name: "吉卜力风格",
    nameEn: "Ghibli Style",
    description: "灵感源自吉卜力工作室动画的设计风格，温暖柔和的色调、手绘质感、自然元素和梦幻氛围，传递治愈与诗意。",
    cover: "/styles/ghibli-style.svg",
    styleType: "visual",
    tags: ["expressive", "retro"],
    category: "expressive",
    colors: {
      primary: "#7cb9a8",
      secondary: "#f4e4bc",
      accent: ["#e8a87c", "#85cdca", "#c38d94"],
    },
    keywords: ["吉卜力", "宫崎骏", "手绘", "治愈", "自然", "梦幻", "动画"],
  },
  {
    slug: "material-design",
    name: "材料设计",
    nameEn: "Material Design",
    description: "Google 推出的设计系统，基于纸张和墨水的隐喻，强调层次、动效、大胆色彩和响应式交互，是现代移动端设计的标准。",
    cover: "/styles/material-design.svg",
    styleType: "visual",
    tags: ["modern", "brand-inspired"],
    category: "modern",
    colors: {
      primary: "#6200ee",
      secondary: "#03dac6",
      accent: ["#ff0266", "#ffde03", "#00c853"],
    },
    keywords: ["Material", "Google", "层次", "动效", "海拔", "涟漪", "卡片"],
  },
  {
    slug: "fluent-design",
    name: "流利设计",
    nameEn: "Fluent Design",
    description: "微软推出的设计系统，融合了光效、深度、动效、材质和缩放五大元素，打造自然直观的跨平台体验。",
    cover: "/styles/fluent-design.svg",
    styleType: "visual",
    tags: ["modern", "brand-inspired"],
    category: "modern",
    colors: {
      primary: "#0078d4",
      secondary: "#106ebe",
      accent: ["#ffb900", "#e81123", "#00cc6a"],
    },
    keywords: ["Fluent", "微软", "亚克力", "Reveal", "光效", "深度", "动效"],
  },
  // 新增风格 - 批次3（视觉风格）
  {
    slug: "comic-style",
    name: "漫画风格",
    nameEn: "Comic Style",
    description: "灵感源自漫画书和日式漫画的设计风格，浓重的墨线边框、网点填充、对话气泡、动作线和分镜面板布局，充满故事感和视觉冲击力。",
    cover: "/styles/comic-style.svg",
    styleType: "visual",
    tags: ["expressive", "high-contrast"],
    category: "expressive",
    colors: {
      primary: "#1a1a1a",
      secondary: "#ffffff",
      accent: ["#ff3333", "#ffcc00", "#3366ff", "#33cc33"],
    },
    keywords: ["漫画", "manga", "网点", "对话气泡", "分镜", "动作线", "墨线"],
  },
  {
    slug: "sketch-style",
    name: "铅笔手绘风",
    nameEn: "Sketch Style",
    description: "模拟铅笔手绘的设计风格，不规则线条边框、纸张纹理背景、手写字体感、素描阴影和涂鸦装饰，传达亲切温暖的手工质感。",
    cover: "/styles/sketch-style.svg",
    styleType: "visual",
    tags: ["expressive", "retro"],
    category: "expressive",
    colors: {
      primary: "#2c2c2c",
      secondary: "#f5f0e8",
      accent: ["#e74c3c", "#3498db", "#27ae60", "#f39c12"],
    },
    keywords: ["手绘", "铅笔", "素描", "纸张", "手写", "涂鸦", "不规则"],
  },
  {
    slug: "watercolor-style",
    name: "水彩画风",
    nameEn: "Watercolor Style",
    description: "灵感源自水彩画的设计风格，柔和的颜色渐变、模糊的边缘效果、纸张质感背景和流动的色彩扩散，传递艺术感与诗意。",
    cover: "/styles/watercolor-style.svg",
    styleType: "visual",
    tags: ["expressive", "minimal"],
    category: "expressive",
    colors: {
      primary: "#4a6fa5",
      secondary: "#faf8f5",
      accent: ["#e8a87c", "#85cdca", "#c38d94", "#d4a373"],
    },
    keywords: ["水彩", "渐变", "柔和", "纸张", "艺术", "流动", "诗意"],
  },
  // 新增布局风格 - 批次3
  {
    slug: "f-pattern-layout",
    name: "F型布局",
    nameEn: "F-Pattern Layout",
    description: "基于眼动追踪研究的F型扫描布局，用户视线从左上角开始，沿顶部水平扫描后向下移动，适合内容密集型页面、博客文章和新闻列表。",
    cover: "/styles/f-pattern-layout.svg",
    styleType: "layout",
    tags: ["modern", "responsive"],
    category: "modern",
    colors: {
      primary: "#1a1a2e",
      secondary: "#f8f9fa",
      accent: ["#e63946", "#457b9d", "#2a9d8f", "#e9c46a"],
    },
    keywords: ["F型", "眼动", "内容优先", "扫描", "阅读", "博客", "新闻"],
    compatibleWith: ["editorial", "corporate-clean", "minimalist-flat", "notion-style", "swiss-style"],
  },
  {
    slug: "z-pattern-layout",
    name: "Z型布局",
    nameEn: "Z-Pattern Layout",
    description: "基于眼动追踪的Z型扫描布局，视线从左上到右上，斜穿到左下再到右下，形成Z字路径。适合着陆页、营销页面和简洁信息展示。",
    cover: "/styles/z-pattern-layout.svg",
    styleType: "layout",
    tags: ["modern", "responsive"],
    category: "modern",
    colors: {
      primary: "#0f172a",
      secondary: "#ffffff",
      accent: ["#6366f1", "#06b6d4", "#f59e0b", "#ec4899"],
    },
    keywords: ["Z型", "着陆页", "营销", "视觉引导", "CTA", "扫描路径"],
    compatibleWith: ["modern-gradient", "apple-style", "stripe-style", "minimalist-flat", "corporate-clean"],
  },
  {
    slug: "holy-grail-layout",
    name: "圣杯布局",
    nameEn: "Holy Grail Layout",
    description: "经典的三栏式网页布局，由固定页头、三列中间区域（左侧导航、主内容、右侧边栏）和固定页脚组成，是Web设计的基础布局范式。",
    cover: "/styles/holy-grail-layout.svg",
    styleType: "layout",
    tags: ["modern", "responsive"],
    category: "modern",
    colors: {
      primary: "#1e293b",
      secondary: "#f1f5f9",
      accent: ["#3b82f6", "#10b981", "#f59e0b", "#ef4444"],
    },
    keywords: ["三栏", "圣杯", "经典", "页头", "页脚", "侧边栏", "导航"],
    compatibleWith: ["corporate-clean", "editorial", "notion-style", "minimalist-flat", "dark-mode"],
  },
  {
    slug: "dashboard-layout",
    name: "仪表盘布局",
    nameEn: "Dashboard Layout",
    description: "数据驱动的仪表盘布局，包含侧边导航、顶部工具栏、多模块数据面板和图表区域，适合后台管理系统、数据分析平台和监控面板。",
    cover: "/styles/dashboard-layout.svg",
    styleType: "layout",
    tags: ["modern", "responsive"],
    category: "modern",
    colors: {
      primary: "#111827",
      secondary: "#f9fafb",
      accent: ["#6366f1", "#10b981", "#f59e0b", "#ef4444"],
    },
    keywords: ["仪表盘", "数据", "面板", "图表", "监控", "后台", "分析"],
    compatibleWith: ["corporate-clean", "dark-mode", "minimalist-flat", "fluent-design", "material-design"],
  },
  // 新增风格 - 批次4
  {
    slug: "scandinavian",
    name: "北欧极简风",
    nameEn: "Scandinavian Minimalism",
    description: "源自北欧的温暖极简设计，强调自然材质、舒适留白、木质色调和Hygge生活美学，营造宁静温馨的视觉体验。",
    cover: "/styles/scandinavian.jpg",
    styleType: "visual",
    tags: ["minimal", "modern"],
    category: "minimal",
    colors: {
      primary: "#3d3d3d",
      secondary: "#f5f0eb",
      accent: ["#5a7a6b", "#7ba0b8", "#c9a88c"],
    },
    keywords: ["北欧", "斯堪的纳维亚", "Hygge", "木质", "自然", "温暖", "留白", "舒适"],
  },
  {
    slug: "steampunk",
    name: "蒸汽朋克",
    nameEn: "Steampunk",
    description: "维多利亚时代与工业革命的融合美学，铜黄金属质感、齿轮装饰、铆钉面板和复古仪表，呈现精密机械的浪漫幻想。",
    cover: "/styles/steampunk.jpg",
    styleType: "visual",
    tags: ["retro", "expressive"],
    category: "retro",
    colors: {
      primary: "#b5882c",
      secondary: "#2a1f14",
      accent: ["#c87533", "#8a8a8a", "#8b2500"],
    },
    keywords: ["蒸汽朋克", "维多利亚", "齿轮", "铜", "工业", "复古", "机械", "黄铜"],
  },
  {
    slug: "cel-shading",
    name: "赛璐璐动画风",
    nameEn: "Cel Shading",
    description: "模拟传统动画赛璐璐片的渲染风格，粗黑轮廓线、平面色块填充、无渐变阴影和鲜艳饱和色彩，充满卡通游戏的活力感。",
    cover: "/styles/cel-shading.jpg",
    styleType: "visual",
    tags: ["expressive", "high-contrast"],
    category: "expressive",
    colors: {
      primary: "#1a1a2e",
      secondary: "#fafaf5",
      accent: ["#e63946", "#4ea8de", "#2ecc71", "#f1c40f"],
    },
    keywords: ["赛璐璐", "卡通", "轮廓线", "平面阴影", "动画", "游戏", "toon", "bold"],
  },
  {
    slug: "wabi-sabi",
    name: "侘寂风",
    nameEn: "Wabi-Sabi",
    description: "日本侘寂美学的数字化呈现，崇尚不完美之美、自然衰老之雅和极致留白之禅，以墨色、茶色和纸张质感传递东方诗意。",
    cover: "/styles/wabi-sabi.jpg",
    styleType: "visual",
    tags: ["minimal", "expressive"],
    category: "minimal",
    colors: {
      primary: "#3a3a3a",
      secondary: "#f2ede4",
      accent: ["#8a9a7b", "#b5a78c", "#8b6f4e"],
    },
    keywords: ["侘寂", "日式", "禅", "不完美", "留白", "Ma", "纸张", "自然", "东方"],
  },
  // 新增风格 - 批次5（艺术感和二次元风格）
  {
    slug: "acid-graphics",
    name: "酸性平面设计",
    nameEn: "Acid Graphics",
    description: "90年代锐舞文化的荧光迷幻美学，高饱和度霓虹色、扭曲字体、液态图形和迷幻视觉效果，创造强烈的视觉冲击。",
    cover: "/styles/acid-graphics.jpg",
    styleType: "visual",
    tags: ["expressive", "high-contrast"],
    category: "expressive",
    colors: {
      primary: "#00ff41",
      secondary: "#0a0a0a",
      accent: ["#ff006e", "#ffea00", "#b900ff"],
    },
    keywords: ["酸性", "荧光", "迷幻", "锐舞", "霓虹", "distorted", "psychedelic", "rave"],
  },
  {
    slug: "hand-drawn-doodle",
    name: "手绘涂鸦风",
    nameEn: "Hand-Drawn Doodle",
    description: "手工绘制的温暖美学，不规则线条、涂鸦装饰、手写字体和纸张质感，营造友好亲切、充满人情味的设计氛围。",
    cover: "/styles/hand-drawn-doodle.jpg",
    styleType: "visual",
    tags: ["expressive", "modern"],
    category: "expressive",
    colors: {
      primary: "#2c2c2c",
      secondary: "#fffef9",
      accent: ["#4a90e2", "#ffd93d", "#ff6b9d"],
    },
    keywords: ["手绘", "涂鸦", "手工", "sketchy", "playful", "friendly", "doodle", "handwritten"],
  },
  {
    slug: "swiss-poster",
    name: "瑞士海报",
    nameEn: "Swiss Poster",
    description: "音乐节和文化海报的实验性平面设计，巨大字体排版、严格网格系统、黑白红配色和极简主义的视觉冲击力。",
    cover: "/styles/swiss-poster.jpg",
    styleType: "visual",
    tags: ["minimal", "high-contrast"],
    category: "minimal",
    colors: {
      primary: "#000000",
      secondary: "#ffffff",
      accent: ["#ff0000", "#0066ff", "#ffff00"],
    },
    keywords: ["瑞士", "海报", "实验", "typography", "bold", "grid", "festival", "poster"],
  },
  {
    slug: "watercolor-art",
    name: "水彩艺术",
    nameEn: "Watercolor Art",
    description: "传统水彩画的数字化演绎，柔和色彩晕染、透明层叠效果、有机笔触和纸张纹理，呈现优雅梦幻的艺术气质。",
    cover: "/styles/watercolor-art.jpg",
    styleType: "visual",
    tags: ["expressive", "modern"],
    category: "expressive",
    colors: {
      primary: "#ffd1dc",
      secondary: "#f7f4ea",
      accent: ["#87ceeb", "#98d8c8", "#e6e6fa"],
    },
    keywords: ["水彩", "艺术", "柔和", "晕染", "watercolor", "artistic", "soft", "dreamy"],
  },
  {
    slug: "glitch-art",
    name: "故障艺术",
    nameEn: "Glitch Art",
    description: "数字损坏美学，像素错位、RGB色彩分离、扫描线、信号失真效果，展现数字时代独特的美学语言。",
    cover: "/styles/glitch-art.jpg",
    styleType: "visual",
    tags: ["expressive", "high-contrast"],
    category: "expressive",
    colors: {
      primary: "#00ffff",
      secondary: "#000000",
      accent: ["#ff00ff", "#ffff00", "#00ff00"],
    },
    keywords: ["故障", "数字", "RGB", "distortion", "glitch", "corruption", "digital", "error"],
  },
  {
    slug: "shoujo-manga",
    name: "少女漫画",
    nameEn: "Shoujo Manga",
    description: "日本少女漫画的梦幻美学，花瓣飞舞、星光闪烁、柔美线条和粉色基调，营造浪漫唯美的二次元氛围。",
    cover: "/styles/shoujo-manga.jpg",
    styleType: "visual",
    tags: ["expressive", "modern"],
    category: "expressive",
    colors: {
      primary: "#ffb3d9",
      secondary: "#fff5f8",
      accent: ["#c8a2e0", "#ffd700", "#ffb6c1"],
    },
    keywords: ["少女漫画", "动漫", "粉色", "花瓣", "shoujo", "manga", "sparkle", "romantic"],
  },
  {
    slug: "pixel-anime",
    name: "像素动漫",
    nameEn: "Pixel Anime",
    description: "8-bit像素艺术与动漫文化的结合，复古游戏风格、像素化角色、Q版造型和鲜艳配色，唤起怀旧的游戏记忆。",
    cover: "/styles/pixel-anime.jpg",
    styleType: "visual",
    tags: ["retro", "expressive"],
    category: "retro",
    colors: {
      primary: "#ff6b9d",
      secondary: "#2d2d2d",
      accent: ["#4ecdc4", "#ffe66d", "#a8e6cf"],
    },
    keywords: ["像素", "动漫", "8-bit", "复古", "pixel", "anime", "retro", "game"],
  },
  {
    slug: "neon-samurai",
    name: "霓虹武士",
    nameEn: "Neon Samurai",
    description: "日本传统武士道与赛博朋克霓虹的融合，武士刀剪影、日文汉字、浮世绘元素和霓虹光效，东方与未来的碰撞。",
    cover: "/styles/neon-samurai.jpg",
    styleType: "visual",
    tags: ["expressive", "high-contrast"],
    category: "expressive",
    colors: {
      primary: "#ff0055",
      secondary: "#0a0a0a",
      accent: ["#00d9ff", "#b900ff", "#ff6600"],
    },
    keywords: ["霓虹", "武士", "日本", "赛博朋克", "samurai", "neon", "cyberpunk", "Japanese"],
  },
  // 新增风格 - 批次6（艺术流派 + 亚文化 + 二次元）
  {
    slug: "art-nouveau",
    name: "新艺术运动",
    nameEn: "Art Nouveau",
    description: "19世纪末的有机装饰艺术，以自然花卉藤蔓的优雅曲线、孔雀羽毛纹理和慕夏风格的女性美感，呈现华丽精致的装饰主义。",
    cover: "/styles/art-nouveau.jpg",
    styleType: "visual",
    tags: ["expressive", "retro"],
    category: "expressive",
    colors: {
      primary: "#2d5a27",
      secondary: "#f4eed7",
      accent: ["#c5993a", "#7b5ea7", "#c27c5a"],
    },
    keywords: ["新艺术", "慕夏", "藤蔓", "花卉", "曲线", "装饰", "art nouveau", "organic"],
  },
  {
    slug: "surrealism",
    name: "超现实主义",
    nameEn: "Surrealism",
    description: "打破现实逻辑的梦境美学，不合理的空间拼接、融化变形的物体、漂浮的场景和超现实光影，展现潜意识的奇幻世界。",
    cover: "/styles/surrealism.jpg",
    styleType: "visual",
    tags: ["expressive", "modern"],
    category: "expressive",
    colors: {
      primary: "#1a1a4e",
      secondary: "#f5e6d3",
      accent: ["#c9a046", "#e8a0b4", "#5bc0be"],
    },
    keywords: ["超现实", "达利", "梦境", "变形", "surreal", "dream", "dali", "fantasy"],
  },
  {
    slug: "ukiyo-e",
    name: "浮世绘数字风",
    nameEn: "Ukiyo-e Digital",
    description: "日本江户时代木版画的数字化演绎，海浪纹、和风花纹、平面透视和锦绘色彩，呈现东方传统版画的独特韵味。",
    cover: "/styles/ukiyo-e.jpg",
    styleType: "visual",
    tags: ["retro", "expressive"],
    category: "retro",
    colors: {
      primary: "#1a3a5c",
      secondary: "#f5e6c8",
      accent: ["#c23030", "#d4a017", "#2d5a27"],
    },
    keywords: ["浮世绘", "版画", "日本", "葛饰北斋", "ukiyo-e", "woodblock", "wave", "edo"],
  },
  {
    slug: "gothic",
    name: "哥特式",
    nameEn: "Gothic",
    description: "中世纪哥特式建筑与暗黑美学的融合，尖拱窗、玫瑰花窗、深色调和手抄本装饰，营造神秘庄严的视觉氛围。",
    cover: "/styles/gothic.jpg",
    styleType: "visual",
    tags: ["expressive", "high-contrast"],
    category: "expressive",
    colors: {
      primary: "#1a0a2e",
      secondary: "#2a1a3e",
      accent: ["#8b0000", "#d4a017", "#4a4a6a"],
    },
    keywords: ["哥特", "中世纪", "教堂", "暗黑", "gothic", "cathedral", "medieval", "dark"],
  },
  {
    slug: "outrun",
    name: "Outrun 复古未来",
    nameEn: "Outrun Retro-Future",
    description: "80年代复古未来主义的视觉盛宴，落日渐变天空、棕榈树剪影、网格地平线和跑车轮廓，充满怀旧的未来浪漫。",
    cover: "/styles/outrun.jpg",
    styleType: "visual",
    tags: ["retro", "expressive"],
    category: "retro",
    colors: {
      primary: "#ff6ec7",
      secondary: "#0a0020",
      accent: ["#00d4ff", "#ff4500", "#ffdd00"],
    },
    keywords: ["outrun", "复古未来", "落日", "80年代", "retrowave", "sunset", "grid", "neon"],
  },
  {
    slug: "dark-academia",
    name: "暗黑学院风",
    nameEn: "Dark Academia",
    description: "古典学院美学与暗色调的结合，图书馆、皮革、古典文学、深色木质和手写花体字，营造知性神秘的书卷气息。",
    cover: "/styles/dark-academia.jpg",
    styleType: "visual",
    tags: ["retro", "minimal"],
    category: "retro",
    colors: {
      primary: "#2c1810",
      secondary: "#f5efe0",
      accent: ["#8b6914", "#4a6741", "#6b3a3a"],
    },
    keywords: ["学院", "暗黑", "图书馆", "古典", "academia", "library", "classical", "scholar"],
  },
  {
    slug: "cottagecore",
    name: "田园核",
    nameEn: "Cottagecore",
    description: "回归自然的乡村田园美学，花卉刺绣、手工编织、蘑菇图案和蜂蜜色调，营造温馨治愈的田园诗意。",
    cover: "/styles/cottagecore.jpg",
    styleType: "visual",
    tags: ["expressive", "modern"],
    category: "expressive",
    colors: {
      primary: "#6b4423",
      secondary: "#faf5e4",
      accent: ["#d4a373", "#81b29a", "#e07a5f"],
    },
    keywords: ["田园", "乡村", "花卉", "手工", "cottage", "pastoral", "floral", "handmade"],
  },
  {
    slug: "risograph",
    name: "Risograph 印刷风",
    nameEn: "Risograph Print",
    description: "日本理想科学Riso印刷机的独特美学，双色叠印、半调网点、印刷错位和颗粒质感，呈现手工印刷的实验性魅力。",
    cover: "/styles/risograph.jpg",
    styleType: "visual",
    tags: ["expressive", "modern"],
    category: "expressive",
    colors: {
      primary: "#ff517c",
      secondary: "#f5f0e8",
      accent: ["#0078bf", "#ff8b3a", "#00b89f"],
    },
    keywords: ["Risograph", "印刷", "叠印", "网点", "riso", "print", "halftone", "overlay"],
  },
  {
    slug: "mecha",
    name: "机甲风",
    nameEn: "Mecha",
    description: "高达与EVA风格的机甲战斗界面，科技面板、警告标识、机械蓝图和战术HUD，呈现精密机械的热血战斗美学。",
    cover: "/styles/mecha.jpg",
    styleType: "visual",
    tags: ["high-contrast", "modern"],
    category: "expressive",
    colors: {
      primary: "#c4a000",
      secondary: "#0d1117",
      accent: ["#2d4a1e", "#cc3300", "#4a90d9"],
    },
    keywords: ["机甲", "高达", "EVA", "战斗", "mecha", "gundam", "tactical", "robot"],
  },
  {
    slug: "gothic-lolita",
    name: "哥特萝莉",
    nameEn: "Gothic Lolita",
    description: "维多利亚蕾丝与暗黑美学的优雅交融，黑色丝带、十字架装饰、玫瑰花纹和精致花边，呈现黑暗中的精致浪漫。",
    cover: "/styles/gothic-lolita.jpg",
    styleType: "visual",
    tags: ["expressive", "retro"],
    category: "expressive",
    colors: {
      primary: "#1a1a2e",
      secondary: "#0e0e18",
      accent: ["#8b0000", "#4a0e3c", "#d4af37"],
    },
    keywords: ["哥特萝莉", "蕾丝", "维多利亚", "洛丽塔", "gothic lolita", "lace", "victorian", "dark"],
  },
  {
    slug: "cyber-chinese",
    name: "赛博中华",
    nameEn: "Cyber Chinese",
    description: "中华传统纹样与赛博朋克科技的碰撞融合，龙凤图腾、篆刻印章、朱红金色搭配霓虹蓝紫，呈现东方未来主义。",
    cover: "/styles/cyber-chinese.jpg",
    styleType: "visual",
    tags: ["expressive", "high-contrast"],
    category: "expressive",
    colors: {
      primary: "#cc1a1a",
      secondary: "#0a0a0f",
      accent: ["#d4a017", "#00d4ff", "#8b00ff"],
    },
    keywords: ["赛博中华", "龙", "朱红", "霓虹", "cyber chinese", "dragon", "eastern", "futurism"],
  },
];

/**
 * Get all styles metadata (lightweight, for client components)
 */
export function getAllStylesMeta(): StyleMeta[] {
  return stylesMeta;
}

/**
 * Get a single style's metadata by slug
 */
export function getStyleMetaBySlug(slug: string): StyleMeta | undefined {
  return stylesMeta.find((style) => style.slug === slug);
}
