module.exports=[918622,(e,t,r)=>{t.exports=e.x("next/dist/compiled/next-server/app-page-turbo.runtime.prod.js",()=>require("next/dist/compiled/next-server/app-page-turbo.runtime.prod.js"))},556704,(e,t,r)=>{t.exports=e.x("next/dist/server/app-render/work-async-storage.external.js",()=>require("next/dist/server/app-render/work-async-storage.external.js"))},832319,(e,t,r)=>{t.exports=e.x("next/dist/server/app-render/work-unit-async-storage.external.js",()=>require("next/dist/server/app-render/work-unit-async-storage.external.js"))},324725,(e,t,r)=>{t.exports=e.x("next/dist/server/app-render/after-task-async-storage.external.js",()=>require("next/dist/server/app-render/after-task-async-storage.external.js"))},270406,(e,t,r)=>{t.exports=e.x("next/dist/compiled/@opentelemetry/api",()=>require("next/dist/compiled/@opentelemetry/api"))},193695,(e,t,r)=>{t.exports=e.x("next/dist/shared/lib/no-fallback-error.external.js",()=>require("next/dist/shared/lib/no-fallback-error.external.js"))},305891,e=>{"use strict";var t=e.i(397764),r=e.i(333902),n=e.i(545475),a=e.i(622736),s=e.i(951683),o=e.i(834857),i=e.i(154137),l=e.i(359207),d=e.i(550419),p=e.i(663859),u=e.i(398368),c=e.i(68300),h=e.i(103152),y=e.i(146739),g=e.i(404155),m=e.i(193695);e.i(765892);var x=e.i(383239),f=e.i(391173),v=e.i(861014),R=e.i(335424),$=e.i(885542),w=e.i(755647);async function b(e,{params:t}){let{slug:r}=await t,n=(0,f.getStyleBySlug)(r);return n?new Response(function(e){let{style:t,tokens:r,includeRecipes:n=!0,includeArchetypes:a=!0,includeExamples:s=!0,includeForbidden:o=!0}=e,i=[];if(i.push(`---
name: ${t.slug}
version: 1.0.0
description: ${t.nameEn} design style for web interfaces
keywords: [${t.keywords.slice(0,5).join(", ")}]
author: StyleKit
style_type: ${t.styleType||"visual"}
---`),i.push(`# ${t.nameEn} Style

## Overview
${t.description}

## Philosophy
${t.philosophy.split("\n\n")[0]}`),r&&i.push(`## Design Tokens

### Border
- Width: \`${r.border.width}\`
- Color: \`${r.border.color}\`
- Radius: \`${r.border.radius}\`

### Shadow
- Small: \`${r.shadow.sm}\`
- Medium: \`${r.shadow.md}\`
- Large: \`${r.shadow.lg}\`
- Hover: \`${r.shadow.hover}\`

### Typography
- Heading: \`${r.typography.heading}\`
- Body: \`${r.typography.body}\`
- Hero: \`${r.typography.sizes.hero}\`
- H1: \`${r.typography.sizes.h1}\`
- Body: \`${r.typography.sizes.body}\`

### Spacing
- Section: \`${r.spacing.section}\`
- Container: \`${r.spacing.container}\`
- Card: \`${r.spacing.card}\`

### Colors
- Primary BG: \`${r.colors.background.primary}\`
- Secondary BG: \`${r.colors.background.secondary}\`
- Primary Text: \`${r.colors.text.primary}\`
- Primary Button: \`${r.colors.button.primary}\``),n){let e=(0,R.getStyleRecipes)(t.slug);if(e)for(let[,t]of(i.push("## Component Recipes"),Object.entries(e.recipes))){let e=Object.entries(t.variants).map(([,e])=>`- ${e.label}: \`${e.classes.join(" ")}\``).join("\n"),r=t.skeleton.baseClasses.join(" ");i.push(`### ${t.name}
- Base: \`${r}\`
${e}`),t.states?.hover&&i.push(`- Hover: \`${t.states.hover.join(" ")}\``)}}if(o&&r?.forbidden){let e=r.forbidden.classes.slice(0,10).map(e=>`- \`${e}\``).join("\n"),n=r.forbidden.patterns.slice(0,5).map(e=>`- Pattern: \`${e}\``).join("\n");i.push(`## Forbidden Patterns
These classes must NEVER be used in ${t.nameEn} style:

${e}

${n}

### Why:
${Object.entries(r.forbidden.reasons).slice(0,3).map(([e,t])=>`- \`${e}\`: ${t}`).join("\n")}`)}if(i.push(`## Do's
${t.doList.map(e=>`- ${e}`).join("\n")}

## Don'ts
${t.dontList.map(e=>`- ${e}`).join("\n")}`),a){let e=(0,$.getArchetypesForStyle)(t.slug);if(e.length>0){let t=e.slice(0,6).map(e=>`- \`${e.id}\`: ${e.description}`).join("\n");i.push(`## Layout Archetypes
${t}`)}}return s&&i.push(`## Example Usage

\`\`\`
Generate a landing page with:
- Style: ${t.slug}
- Archetype: landing-hero-centered
- Sections: hero, features, cta, footer
- Components: heading (hero variant), button (primary, lg), card (default)
\`\`\`

### Example Prompts:
${t.examplePrompts?.slice(0,3).map(e=>`- "${e.title}"`).join("\n")||"- Create a landing page in this style"}`),i.push(`---
Generated by StyleKit \xb7 https://stylekit.dev
Style: ${t.name} (${t.nameEn})`),i.join("\n\n")}({style:n,tokens:(0,v.getStyleTokens)(r)}),{headers:{"Content-Type":"text/markdown; charset=utf-8","Content-Disposition":`attachment; filename="${r}-SKILL.md"`}}):w.NextResponse.json({error:"Style not found"},{status:404})}e.s(["GET",()=>b],886921);var E=e.i(886921);let C=new t.AppRouteRouteModule({definition:{kind:r.RouteKind.APP_ROUTE,page:"/api/styles/[slug]/skill-pack/route",pathname:"/api/styles/[slug]/skill-pack",filename:"route",bundlePath:""},distDir:"/tmp/stylekit-next",relativeProjectDir:"",resolvedPagePath:"[project]/app/api/styles/[slug]/skill-pack/route.ts",nextConfigOutput:"",userland:E}),{workAsyncStorage:k,workUnitAsyncStorage:S,serverHooks:j}=C;function A(){return(0,n.patchFetch)({workAsyncStorage:k,workUnitAsyncStorage:S})}async function T(e,t,n){C.isDev&&(0,a.addRequestMeta)(e,"devRequestTimingInternalsEnd",process.hrtime.bigint());let f="/api/styles/[slug]/skill-pack/route";f=f.replace(/\/index$/,"")||"/";let v=await C.prepare(e,t,{srcPage:f,multiZoneDraftMode:!1});if(!v)return t.statusCode=400,t.end("Bad Request"),null==n.waitUntil||n.waitUntil.call(n,Promise.resolve()),null;let{buildId:R,params:$,nextConfig:w,parsedUrl:b,isDraftMode:E,prerenderManifest:k,routerServerContext:S,isOnDemandRevalidate:j,revalidateOnlyGenerated:A,resolvedPathname:T,clientReferenceManifest:P,serverActionsManifest:N}=v,O=(0,i.normalizeAppPath)(f),H=!!(k.dynamicRoutes[O]||k.routes[T]),_=async()=>((null==S?void 0:S.render404)?await S.render404(e,t,b,!1):t.end("This page could not be found"),null);if(H&&!E){let e=!!k.routes[T],t=k.dynamicRoutes[O];if(t&&!1===t.fallback&&!e){if(w.experimental.adapterPath)return await _();throw new m.NoFallbackError}}let q=null;!H||C.isDev||E||(q="/index"===(q=T)?"/":q);let D=!0===C.isDev||!H,U=H&&!D;N&&P&&(0,o.setManifestsSingleton)({page:f,clientReferenceManifest:P,serverActionsManifest:N});let I=e.method||"GET",B=(0,s.getTracer)(),M=B.getActiveScopeSpan(),K={params:$,prerenderManifest:k,renderOpts:{experimental:{authInterrupts:!!w.experimental.authInterrupts},cacheComponents:!!w.cacheComponents,supportsDynamicResponse:D,incrementalCache:(0,a.getRequestMeta)(e,"incrementalCache"),cacheLifeProfiles:w.cacheLife,waitUntil:n.waitUntil,onClose:e=>{t.on("close",e)},onAfterTaskError:void 0,onInstrumentationRequestError:(t,r,n,a)=>C.onRequestError(e,t,n,a,S)},sharedContext:{buildId:R}},L=new l.NodeNextRequest(e),F=new l.NodeNextResponse(t),G=d.NextRequestAdapter.fromNodeNextRequest(L,(0,d.signalFromNodeResponse)(t));try{let o=async e=>C.handle(G,K).finally(()=>{if(!e)return;e.setAttributes({"http.status_code":t.statusCode,"next.rsc":!1});let r=B.getRootSpanAttributes();if(!r)return;if(r.get("next.span_type")!==p.BaseServerSpan.handleRequest)return void console.warn(`Unexpected root span type '${r.get("next.span_type")}'. Please report this Next.js issue https://github.com/vercel/next.js`);let n=r.get("next.route");if(n){let t=`${I} ${n}`;e.setAttributes({"next.route":n,"http.route":n,"next.span_name":t}),e.updateName(t)}else e.updateName(`${I} ${f}`)}),i=!!(0,a.getRequestMeta)(e,"minimalMode"),l=async a=>{var s,l;let d=async({previousCacheEntry:r})=>{try{if(!i&&j&&A&&!r)return t.statusCode=404,t.setHeader("x-nextjs-cache","REVALIDATED"),t.end("This page could not be found"),null;let s=await o(a);e.fetchMetrics=K.renderOpts.fetchMetrics;let l=K.renderOpts.pendingWaitUntil;l&&n.waitUntil&&(n.waitUntil(l),l=void 0);let d=K.renderOpts.collectedTags;if(!H)return await (0,c.sendResponse)(L,F,s,K.renderOpts.pendingWaitUntil),null;{let e=await s.blob(),t=(0,h.toNodeOutgoingHttpHeaders)(s.headers);d&&(t[g.NEXT_CACHE_TAGS_HEADER]=d),!t["content-type"]&&e.type&&(t["content-type"]=e.type);let r=void 0!==K.renderOpts.collectedRevalidate&&!(K.renderOpts.collectedRevalidate>=g.INFINITE_CACHE)&&K.renderOpts.collectedRevalidate,n=void 0===K.renderOpts.collectedExpire||K.renderOpts.collectedExpire>=g.INFINITE_CACHE?void 0:K.renderOpts.collectedExpire;return{value:{kind:x.CachedRouteKind.APP_ROUTE,status:s.status,body:Buffer.from(await e.arrayBuffer()),headers:t},cacheControl:{revalidate:r,expire:n}}}}catch(t){throw(null==r?void 0:r.isStale)&&await C.onRequestError(e,t,{routerKind:"App Router",routePath:f,routeType:"route",revalidateReason:(0,u.getRevalidateReason)({isStaticGeneration:U,isOnDemandRevalidate:j})},!1,S),t}},p=await C.handleResponse({req:e,nextConfig:w,cacheKey:q,routeKind:r.RouteKind.APP_ROUTE,isFallback:!1,prerenderManifest:k,isRoutePPREnabled:!1,isOnDemandRevalidate:j,revalidateOnlyGenerated:A,responseGenerator:d,waitUntil:n.waitUntil,isMinimalMode:i});if(!H)return null;if((null==p||null==(s=p.value)?void 0:s.kind)!==x.CachedRouteKind.APP_ROUTE)throw Object.defineProperty(Error(`Invariant: app-route received invalid cache entry ${null==p||null==(l=p.value)?void 0:l.kind}`),"__NEXT_ERROR_CODE",{value:"E701",enumerable:!1,configurable:!0});i||t.setHeader("x-nextjs-cache",j?"REVALIDATED":p.isMiss?"MISS":p.isStale?"STALE":"HIT"),E&&t.setHeader("Cache-Control","private, no-cache, no-store, max-age=0, must-revalidate");let m=(0,h.fromNodeOutgoingHttpHeaders)(p.value.headers);return i&&H||m.delete(g.NEXT_CACHE_TAGS_HEADER),!p.cacheControl||t.getHeader("Cache-Control")||m.get("Cache-Control")||m.set("Cache-Control",(0,y.getCacheControlHeader)(p.cacheControl)),await (0,c.sendResponse)(L,F,new Response(p.value.body,{headers:m,status:p.value.status||200})),null};M?await l(M):await B.withPropagatedContext(e.headers,()=>B.trace(p.BaseServerSpan.handleRequest,{spanName:`${I} ${f}`,kind:s.SpanKind.SERVER,attributes:{"http.method":I,"http.target":e.url}},l))}catch(t){if(t instanceof m.NoFallbackError||await C.onRequestError(e,t,{routerKind:"App Router",routePath:O,routeType:"route",revalidateReason:(0,u.getRevalidateReason)({isStaticGeneration:U,isOnDemandRevalidate:j})},!1,S),H)throw t;return await (0,c.sendResponse)(L,F,new Response(null,{status:500})),null}}e.s(["handler",()=>T,"patchFetch",()=>A,"routeModule",()=>C,"serverHooks",()=>j,"workAsyncStorage",()=>k,"workUnitAsyncStorage",()=>S],305891)}];

//# sourceMappingURL=%5Broot-of-the-server%5D__93e14238._.js.map