import type { MobileLibrary } from "./types";

// `source` records internal curation provenance. Do not render it as a personal Star badge.
export const mobileLibraries: MobileLibrary[] = [
  {
    id: "chunui",
    name: "ChunUI",
    platforms: ["swiftui"],
    category: "design-system",
    summary: {
      zh: "从已上线 iOS 应用提炼的 SwiftUI 设计系统，以灰阶层次、单一品牌色、原生 Sheet 和细腻反馈为核心。",
      en: "A SwiftUI design system extracted from a shipped iOS app, centered on grayscale hierarchy, one brand color, native sheets, and tactile feedback.",
    },
    bestFor: {
      zh: "希望快速建立统一原生 iOS 视觉，并复用按钮、表单、弹层和动效规范的 SwiftUI 项目。",
      en: "SwiftUI apps that need a consistent native iOS visual system for controls, forms, sheets, and motion.",
    },
    caution: {
      zh: "新兴项目；要求 iOS 18.6+ 与 Swift tools 6.2。README 以 main 分支接入，正式项目应先固定版本并验证兼容性。",
      en: "An emerging project requiring iOS 18.6+ and Swift tools 6.2. Its README uses the main branch, so pin a revision and verify compatibility before production use.",
    },
    components: [
      { zh: "主题令牌与字体、间距规范", en: "Theme tokens, type, and spacing" },
      { zh: "按钮、表单与原生 Sheet", en: "Buttons, forms, and native sheets" },
      { zh: "Toast、骨架屏与 Metal 动效", en: "Toasts, skeletons, and Metal effects" },
    ],
    license: "MIT",
    repository: "https://github.com/liseami/ChunUI",
    docs: "https://github.com/liseami/ChunUI#readme",
    checkedAt: "2026-10-04",
    source: "requested",
    scenarios: ["reading", "commerce", "workspace"],
  },
  {
    id: "shipswift",
    name: "ShipSwift",
    platforms: ["swiftui"],
    category: "library",
    summary: {
      zh: "面向 SwiftUI 的组件与页面配方库，覆盖动画、图表、表单反馈和常见应用流程。",
      en: "A SwiftUI component and recipe library spanning animation, charts, form feedback, and common app flows.",
    },
    bestFor: {
      zh: "需要可检查源码、快速搭建图表、引导页、搜索、提醒和支付页面的 iOS 项目。",
      en: "iOS apps that need inspectable source for charts, onboarding, search, feedback, or paywall screens.",
    },
    caution: {
      zh: "MIT 仓库包含可本地复制的组件；README 同时提到需在线服务的 Pro 配方。使用前逐项检查源码、依赖和服务要求。",
      en: "The MIT repository includes components that can be copied locally, while its README also describes Pro recipes served online. Check each source file, dependency, and service requirement before reuse.",
    },
    components: [
      { zh: "SwiftUI 动画与 Metal 背景", en: "SwiftUI motion and Metal backgrounds" },
      { zh: "折线、柱状与环形图表", en: "Line, bar, and ring charts" },
      { zh: "Sheet、搜索、提醒与 Tab", en: "Sheets, search, feedback, and tabs" },
    ],
    license: "MIT",
    repository: "https://github.com/signerlabs/ShipSwift",
    docs: "https://github.com/signerlabs/ShipSwift#readme",
    checkedAt: "2026-10-04",
    source: "starred",
    scenarios: ["reading", "commerce", "workspace"],
  },
  {
    id: "blossom-carousel",
    name: "Blossom Carousel",
    platforms: ["web", "react", "vue"],
    category: "primitive",
    summary: {
      zh: "围绕浏览器原生滚动构建的轮播，触屏保留原生手势，并为鼠标和触控笔补上拖拽。",
      en: "A carousel built on native browser scrolling, preserving touch gestures while adding pointer dragging for mouse and pen.",
    },
    bestFor: {
      zh: "阅读内容画廊、商品图片和横向卡片列表，尤其适合优先保留浏览器滚动体验的页面。",
      en: "Reading galleries, product imagery, and horizontal card rails where native browser scrolling should remain the default.",
    },
    caution: {
      zh: "这是 Web 轮播，不是 iOS 或 Android 原生组件；循环滚动仍标为实验功能。",
      en: "This is a web carousel, not a native iOS or Android component; cyclical scrolling is still marked experimental.",
    },
    components: [
      { zh: "原生滚动与 CSS Scroll Snap", en: "Native scrolling with CSS scroll snap" },
      { zh: "鼠标、触控笔拖拽增强", en: "Pointer drag enhancement" },
      { zh: "前后翻页与圆点导航", en: "Previous/next and dot navigation" },
    ],
    license: "Apache-2.0",
    repository: "https://github.com/jespervos/blossom-carousel",
    docs: "https://www.blossom-carousel.com",
    checkedAt: "2026-10-04",
    source: "starred",
    scenarios: ["reading", "commerce"],
  },
  {
    id: "ant-design-mobile",
    name: "Ant Design Mobile",
    platforms: ["react"],
    category: "design-system",
    summary: {
      zh: "专为移动 Web 设计的 React 组件库，提供表单、选择器、列表与反馈等完整积木。",
      en: "A React component library designed for mobile web, with building blocks for forms, pickers, lists, and feedback.",
    },
    bestFor: {
      zh: "React H5 页面需要现成的移动控件、表单状态和一致的触屏细节。",
      en: "React H5 pages that need ready-made mobile controls, form states, and consistent touch details.",
    },
    caution: {
      zh: "面向浏览器中的 React，不是 React Native；整套默认视觉较强，适合参考或挑选组件；采用时应保持产品自身的品牌样式。",
      en: "It targets React in the browser, not React Native. Its default visual language is strong, so adopt selectively to preserve the product's visual identity.",
    },
    components: [
      { zh: "按钮、表单与输入控件", en: "Buttons, forms, and inputs" },
      { zh: "选择器、日期与动作面板", en: "Pickers, dates, and action sheets" },
      { zh: "列表、标签页与提示", en: "Lists, tabs, and feedback" },
    ],
    license: "MIT",
    repository: "https://github.com/ant-design/ant-design-mobile",
    docs: "https://mobile.ant.design/",
    checkedAt: "2026-10-04",
    source: "research",
    scenarios: ["reading", "commerce", "workspace"],
  },
  {
    id: "vant",
    name: "Vant",
    platforms: ["vue"],
    category: "design-system",
    summary: {
      zh: "轻量、可定制的 Vue 移动 Web 组件库，提供适合手机表单和商城流程的基础控件。",
      en: "A lightweight, customizable Vue component library for mobile web, with practical controls for phone-sized forms and commerce flows.",
    },
    bestFor: {
      zh: "Vue 3 H5、移动商城、报名与资料填写流程。",
      en: "Vue 3 H5 sites, mobile commerce, signup, and data-entry flows.",
    },
    caution: {
      zh: "Vant 是 Vue 组件，不能直接用于 React 项目；当前主线面向 Vue 3，旧 Vue 2 项目需选对应版本。",
      en: "Vant components cannot be used directly in React projects. The current line targets Vue 3; legacy Vue 2 projects need the matching version.",
    },
    components: [
      { zh: "表单、单元格与选择器", en: "Forms, cells, and pickers" },
      { zh: "日历、日期与动作面板", en: "Calendar, date, and action sheets" },
      { zh: "列表、标签与轻提示", en: "Lists, tags, and toast feedback" },
    ],
    license: "MIT",
    repository: "https://github.com/youzan/vant",
    docs: "https://vant-ui.github.io/vant/",
    checkedAt: "2026-10-04",
    source: "research",
    scenarios: ["reading", "commerce", "workspace"],
  },
  {
    id: "ionic",
    name: "Ionic Framework",
    platforms: ["web", "react", "vue"],
    category: "design-system",
    summary: {
      zh: "基于 Web Components 的移动 UI 工具包，可通过 React 或 Vue 适配器构建移动 Web、PWA 和混合应用。",
      en: "A Web Components mobile UI toolkit with React and Vue integrations for mobile web, PWAs, and hybrid apps.",
    },
    bestFor: {
      zh: "需要完整移动应用外壳、跨平台主题、导航与设备能力接入的团队。",
      en: "Teams that need a full mobile app shell, adaptive themes, navigation, and access to device capabilities.",
    },
    caution: {
      zh: "它是一套应用工具链，不只是几个控件；部署原生能力通常还要配合 Capacitor。如果只为现有应用增加单个控件，可以借鉴其模式，无需引入整套框架。",
      en: "It is an app toolkit, not just a few controls. Native deployment usually pairs with Capacitor; a project adding only one control can borrow its patterns without adopting the full stack.",
    },
    components: [
      { zh: "导航栏、标签栏与列表", en: "Navigation bars, tab bars, and lists" },
      { zh: "动作面板、弹窗与提示", en: "Action sheets, modals, and toasts" },
      { zh: "触控手势与平台主题", en: "Touch gestures and platform themes" },
    ],
    license: "MIT",
    repository: "https://github.com/ionic-team/ionic-framework",
    docs: "https://ionicframework.com/docs",
    checkedAt: "2026-10-04",
    source: "research",
    scenarios: ["reading", "commerce", "workspace"],
  },
  {
    id: "framework7",
    name: "Framework7",
    platforms: ["web", "react", "vue"],
    category: "design-system",
    summary: {
      zh: "移动 Web 与混合应用框架，提供 iOS 和 Material 风格的控件、路由及应用结构。",
      en: "A mobile web and hybrid app framework with iOS and Material-style controls, routing, and app structure.",
    },
    bestFor: {
      zh: "想做接近原生应用结构的独立移动 SPA，并需要整套页面与导航控件。",
      en: "Standalone mobile SPAs that need an app-like structure plus a complete set of screens and navigation controls.",
    },
    caution: {
      zh: "它会接管较多应用结构和路由；在已有 Next.js 应用中，更适合作为交互参考或独立原型。",
      en: "It owns much of the app structure and routing, so it is better as a pattern reference or a separate prototype inside an existing Next.js product.",
    },
    components: [
      { zh: "导航栏、底部工具栏与标签页", en: "Navigation bars, toolbars, and tabs" },
      { zh: "弹窗、动作面板与搜索栏", en: "Dialogs, action sheets, and search bars" },
      { zh: "iOS / Material 自适应主题", en: "Adaptive iOS and Material themes" },
    ],
    license: "MIT",
    repository: "https://github.com/framework7io/framework7",
    docs: "https://framework7.io/docs/",
    checkedAt: "2026-10-04",
    source: "research",
    scenarios: ["reading", "commerce", "workspace"],
  },
  {
    id: "swiper",
    name: "Swiper",
    platforms: ["web", "react", "vue"],
    category: "primitive",
    summary: {
      zh: "成熟的触屏滑块与轮播库，支持 React、Vue 和多种导航、分页模块。",
      en: "A mature touch slider and carousel library with React, Vue, and optional navigation and pagination modules.",
    },
    bestFor: {
      zh: "商品图集、横向内容卡片、需要分页或复杂滑动行为的移动 Web。",
      en: "Mobile product galleries, horizontal content rails, and carousels that need pagination or richer slide behavior.",
    },
    caution: {
      zh: "功能范围比单纯轮播更大；普通内容条优先用原生横向滚动，只有需要其手势与模块时再引入。",
      en: "Its feature set is broader than a basic carousel. Prefer native horizontal scrolling for simple rails and add Swiper when its gesture or module features are needed.",
    },
    components: [
      { zh: "滑块与幻灯片", en: "Slider and slides" },
      { zh: "分页点与前后导航", en: "Pagination and next/previous navigation" },
      { zh: "触屏与鼠标拖动", en: "Touch and pointer dragging" },
    ],
    license: "MIT",
    repository: "https://github.com/nolimits4web/swiper",
    docs: "https://swiperjs.com/react",
    checkedAt: "2026-10-04",
    source: "research",
    scenarios: ["reading", "commerce"],
  },
  {
    id: "radix-dialog",
    name: "Radix UI Dialog",
    platforms: ["react"],
    category: "primitive",
    summary: {
      zh: "无样式的 React 对话框基础原语，处理模态层、焦点管理、键盘关闭和屏幕阅读器语义。",
      en: "An unstyled React dialog primitive that handles modal layers, focus management, keyboard dismissal, and screen-reader semantics.",
    },
    bestFor: {
      zh: "需要自己设计视觉的 React Web 弹层、筛选面板和移动端底部面板。",
      en: "React web dialogs, filter panels, and mobile bottom panels that need a custom visual design.",
    },
    caution: {
      zh: "它提供访问性良好的 Dialog 结构，但不自带抽屉拖拽或吸附点；要做 Bottom Sheet 手势仍需由应用补充。",
      en: "It provides an accessible dialog structure, but no drawer dragging or snap points; the app still needs to add bottom-sheet gestures.",
    },
    components: [
      { zh: "Root、Trigger、Portal 与 Overlay", en: "Root, trigger, portal, and overlay" },
      { zh: "Content、Title 与 Description", en: "Content, title, and description" },
      { zh: "焦点捕获、Esc 关闭与读屏语义", en: "Focus trapping, Escape dismissal, and screen-reader semantics" },
    ],
    license: "MIT",
    repository: "https://github.com/radix-ui/primitives",
    docs: "https://www.radix-ui.com/primitives/docs/components/dialog",
    checkedAt: "2026-10-04",
    source: "research",
    scenarios: ["commerce", "workspace"],
  },  {
    id: "react-native-paper",
    name: "React Native Paper",
    platforms: ["react-native"],
    category: "design-system",
    summary: {
      zh: "遵循 Material Design 3 的 React Native 跨平台组件库，支持 iOS、Android 和主题定制。",
      en: "A React Native component library following Material Design 3, with iOS and Android support and theme customization.",
    },
    bestFor: {
      zh: "要快速搭建 Material 风格原生应用，并保持按钮、表单、导航一致的 RN 项目。",
      en: "React Native apps that need a coherent Material-style set of buttons, forms, and navigation.",
    },
    caution: {
      zh: "组件运行在 React Native，不能直接用于普通浏览器 DOM；使用时需设置 PaperProvider 和主题。",
      en: "Its components run in React Native and cannot be used directly in a regular browser DOM; use PaperProvider and configure a theme.",
    },
    components: [
      { zh: "按钮、卡片与列表", en: "Buttons, cards, and lists" },
      { zh: "输入框、选择器与菜单", en: "Inputs, pickers, and menus" },
      { zh: "导航栏、弹窗与主题", en: "App bars, dialogs, and themes" },
    ],
    license: "MIT",
    repository: "https://github.com/callstack/react-native-paper",
    docs: "https://callstack.github.io/react-native-paper/",
    checkedAt: "2026-10-04",
    source: "research",
    scenarios: ["reading", "commerce", "workspace"],
  },
  {
    id: "gorhom-bottom-sheet",
    name: "React Native Bottom Sheet",
    platforms: ["react-native"],
    category: "primitive",
    summary: {
      zh: "带吸附点、手势和键盘处理的原生底部面板，适合 iOS 与 Android 的筛选和详情流程。",
      en: "A native bottom sheet with snapping, gestures, and keyboard handling for filters and detail flows on iOS and Android.",
    },
    bestFor: {
      zh: "React Native 原生应用里的筛选、购物选项、任务操作和可滚动详情面板。",
      en: "React Native apps that need filter sheets, purchase options, task actions, or scrollable detail panels.",
    },
    caution: {
      zh: "需要配套 Reanimated 和 Gesture Handler，并按各自文档完成原生配置；这不是浏览器 DOM 抽屉。",
      en: "It requires Reanimated and Gesture Handler with their native setup steps; it is not a drawer that can be dropped into a Next.js DOM page.",
    },
    components: [
      { zh: "多吸附点 Bottom Sheet", en: "Multi-snap bottom sheet" },
      { zh: "Modal Sheet 与动态高度", en: "Modal sheet and dynamic sizing" },
      { zh: "列表、键盘与滚动协调", en: "Coordinated lists, keyboard, and scrolling" },
    ],
    license: "MIT",
    repository: "https://github.com/gorhom/react-native-bottom-sheet",
    docs: "https://gorhom.dev/react-native-bottom-sheet/",
    checkedAt: "2026-10-04",
    source: "research",
    scenarios: ["commerce", "workspace"],
  },
  {
    id: "tamagui",
    name: "Tamagui",
    platforms: ["web", "react-native"],
    category: "design-system",
    summary: {
      zh: "面向 Web 与 React Native 的通用 React 设计系统，可共享组件、主题和响应式样式。",
      en: "A universal React design system for web and React Native that can share components, themes, and responsive styles.",
    },
    bestFor: {
      zh: "同时维护 Next.js 网站和 Expo 原生应用，并希望复用设计令牌与界面组件的团队。",
      en: "Teams maintaining both a Next.js site and Expo app that want to share design tokens and UI components.",
    },
    caution: {
      zh: "跨端复用需要配置与理解其主题系统；原生端要求 React Native 0.81+ 新架构。仅给当前 Web 页面补移动样式时，引入整套系统成本偏高。",
      en: "Cross-platform reuse brings configuration and theming decisions; native projects require React Native 0.81+ with the New Architecture. It is substantial overhead for styling one existing web page.",
    },
    components: [
      { zh: "通用 Box、Stack 与文本", en: "Universal Box, Stack, and text" },
      { zh: "主题、令牌与响应式变体", en: "Themes, tokens, and responsive variants" },
      { zh: "表单、菜单与弹层控件", en: "Form, menu, and overlay controls" },
    ],
    license: "MIT",
    repository: "https://github.com/tamagui/tamagui",
    docs: "https://tamagui.dev/docs/intro/installation",
    checkedAt: "2026-10-04",
    source: "research",
    scenarios: ["reading", "commerce", "workspace"],
  },
];
