module.exports=[911089,a=>{"use strict";var b=a.i(191873),c=a.i(305769),d=a.i(621269);function e(a){let d=(0,b.getStyleBySlug)(a);return d?{style:d,tokens:(0,c.getStyleTokens)(a)}:null}function f(a){return a.map(a=>`- ${a}`).join("\n")}function g(a){let b=[];return b.push(`- Font (heading): ${a.typography.heading}`),b.push(`- Font (body): ${a.typography.body}`),b.push(`- Border radius: ${a.border.radius}`),b.push(`- Border width: ${a.border.width}`),b.push(`- Border color: ${a.border.color}`),b.push(`- Shadow (sm): ${a.shadow.sm}`),b.push(`- Shadow (md): ${a.shadow.md}`),b.push(`- Shadow (lg): ${a.shadow.lg}`),b.push(`- Shadow (hover): ${a.shadow.hover}`),b.push(`- Spacing (section): ${a.spacing.section}`),b.push(`- Spacing (container): ${a.spacing.container}`),b.push(`- Spacing (card): ${a.spacing.card}`),b.push(`- Transition: ${a.interaction.transition}`),b.join("\n")}function h(a){let b=[];b.push(`- Primary: ${a.colors.primary}`),b.push(`- Secondary: ${a.colors.secondary}`);for(let c=0;c<a.colors.accent.length;c++)b.push(`- Accent ${c+1}: ${a.colors.accent[c]}`);return b.join("\n")}function i(a,b=15){if(!a.forbidden||0===a.forbidden.classes.length)return"";let c=[];for(let d of a.forbidden.classes.slice(0,b)){let b=a.forbidden.reasons[d];c.push(`- \`${d}\`${b?`: ${b}`:""}`)}return c.join("\n")}function j(a){let b=(0,d.getStyleRecipes)(a);if(!b)return"No component recipes available.";let c=[];for(let[a,d]of Object.entries(b.recipes)){let b=d.skeleton.baseClasses.join(" ");c.push(`### ${d.name}`),c.push(`- ID: ${a}`),c.push(`- Base classes: \`${b}\``);let e=Object.entries(d.variants);if(e.length>0)for(let[,a]of(c.push("- Variants:"),e.slice(0,5)))c.push(`  - ${a.label}: \`${a.classes.join(" ")}\``);d.states?.hover&&c.push(`- Hover: \`${d.states.hover.join(" ")}\``),c.push("")}return c.join("\n")}function k(a){let b=e(a);if(!b)return null;let{style:c,tokens:d}=b,k=[];if(k.push(`# Style: ${c.nameEn}
# Generated by StyleKit (https://stylekit.dev)
# Slug: ${c.slug}`),k.push(`## Design Philosophy
${c.philosophy.split("\n\n")[0]}`),k.push(`## Do's
${f(c.doList)}`),k.push(`## Don'ts
${f(c.dontList)}`),k.push(`## AI Rules
${c.aiRules}`),k.push(`## Color Palette
${h(c)}`),d){k.push(`## Token Reference
${g(d)}`);let a=i(d);a&&k.push(`## Forbidden Classes
${a}`)}let l=j(a);return"No component recipes available."!==l&&k.push(`## Component Guidelines
${l}`),k.push(`---
Generated by StyleKit \xb7 https://stylekit.dev
Style: ${c.name} (${c.nameEn})`),k.join("\n\n")}function l(a){let b=e(a);if(!b)return null;let{style:c,tokens:d}=b,k=[];if(k.push(`# StyleKit: ${c.nameEn} Design Rules

> ${c.description}`),k.push(`## Philosophy
${c.philosophy.split("\n\n")[0]}`),k.push(`## Rules

### Do
${f(c.doList)}

### Don't
${f(c.dontList)}

### AI-Specific Rules
${c.aiRules}`),k.push(`## Colors
${h(c)}`),d){k.push(`## Design Tokens
${g(d)}`);let a=i(d);a&&k.push(`## Forbidden Classes
${a}`)}let l=j(a);return"No component recipes available."!==l&&k.push(`## Component Recipes
${l}`),k.push(`---
Generated by StyleKit \xb7 https://stylekit.dev
Style: ${c.name} (${c.nameEn})`),k.join("\n\n")}function m(a){let b=e(a);if(!b)return null;let{style:c,tokens:d}=b,j=[];if(j.push(`# ${c.nameEn} - Windsurf Rules
# Generated by StyleKit

Style: ${c.slug}
Type: ${c.styleType}`),j.push(`## Design Philosophy
${c.philosophy.split("\n\n")[0]}`),j.push(`## Core Rules
${c.aiRules}`),j.push(`## Do
${f(c.doList)}`),j.push(`## Don't
${f(c.dontList)}`),j.push(`## Colors
${h(c)}`),d){j.push(`## Key Tokens
${g(d)}`);let a=i(d);a&&j.push(`## Forbidden
${a}`)}return j.push(`---
Generated by StyleKit \xb7 https://stylekit.dev`),j.join("\n\n")}function n(a){let b=e(a);if(!b)return null;let{style:c,tokens:d}=b,k=[];if(k.push(`# ${c.nameEn} Design Style
# Generated by StyleKit (https://stylekit.dev)

${c.description}`),k.push(`## Philosophy
${c.philosophy.split("\n\n")[0]}`),k.push(`## Do
${f(c.doList)}`),k.push(`## Don't
${f(c.dontList)}`),k.push(`## AI Generation Rules
${c.aiRules}`),k.push(`## Colors
${h(c)}`),d){k.push(`## Design Tokens
${g(d)}`);let a=i(d);a&&k.push(`## Forbidden Classes
${a}`)}let l=j(a);return"No component recipes available."!==l&&k.push(`## Component Reference
${l}`),k.push(`---
Generated by StyleKit \xb7 https://stylekit.dev
Style: ${c.name} (${c.nameEn})`),k.join("\n\n")}function o(a,b){switch(b){case"cursorrules":return k(a);case"claude-rules":return l(a);case"windsurf-rules":return m(a);case"generic":return n(a)}}function p(a,b){switch(b){case"cursorrules":return".cursorrules";case"claude-rules":return`${a}.md`;case"windsurf-rules":return".windsurf-rules";case"generic":return`${a}-rules.md`}}function q(a){switch(a){case"cursorrules":return"text/plain";case"claude-rules":case"windsurf-rules":case"generic":return"text/markdown"}}a.s(["generateClaudeRules",()=>l,"generateCursorRules",()=>k,"generateGenericRules",()=>n,"generateIdeConfig",()=>o,"generateWindsurfRules",()=>m,"getIdeConfigFilename",()=>p,"getIdeConfigMimeType",()=>q])}];

//# sourceMappingURL=lib_export_ide-configs_ts_08a8c726._.js.map