/**
 * Asset metadata system
 *
 * Manages cute cartoon assets generated by AI tools (Gemini, Nano Banana, etc.)
 * Supports categorization, tagging, and integration into UI components
 */

export type AssetCategory =
  | "function"
  | "emotion"
  | "decoration"
  | "character"
  | "background"
  | "icon"
  | "badge";

export type AssetTag =
  | "cute"
  | "playful"
  | "minimal"
  | "colorful"
  | "monochrome"
  | "3d"
  | "flat"
  | "clay"
  | "pastel"
  | "cat";

export interface AssetMeta {
  id: string;
  slug: string;
  name: string;
  nameEn: string;
  description: string;
  image: string;
  thumbnail?: string;
  category: AssetCategory;
  tags: AssetTag[];
  source?: "gemini" | "banana-nano" | "midjourney" | "dalle" | "custom";
  colors?: string[];
  size?: {
    width: number;
    height: number;
  };
  useCases?: string[];
  compatibleStyles?: string[];
  createdAt?: string;
}

/**
 * Asset registry - all available assets
 * Generated from AI icon workflow (Gemini + Claude Code)
 */
export const assetsMeta: AssetMeta[] = [
  // ==================== 功能图标 (Function Icons) ====================
  {
    id: "function-home",
    slug: "function-home",
    name: "首页",
    nameEn: "Home",
    description: "奶油色小猫坐在小房子里，适合首页导航图标",
    image: "/assets/icons/function/function_home.png",
    category: "function",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["导航图标", "首页入口", "返回主页"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "function-settings",
    slug: "function-settings",
    name: "设置",
    nameEn: "Settings",
    description: "奶油色小猫抱着齿轮，适合设置功能图标",
    image: "/assets/icons/function/function_settings.png",
    category: "function",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["设置入口", "偏好设置", "配置选项"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "function-search",
    slug: "function-search",
    name: "搜索",
    nameEn: "Search",
    description: "奶油色小猫拿着放大镜，适合搜索功能图标",
    image: "/assets/icons/function/function_search.png",
    category: "function",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["搜索框", "查找功能", "探索入口"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "function-notification",
    slug: "function-notification",
    name: "通知",
    nameEn: "Notification",
    description: "奶油色小猫头顶铃铛，适合通知提醒图标",
    image: "/assets/icons/function/function_notification.png",
    category: "function",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["消息通知", "提醒入口", "铃铛图标"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "function-profile",
    slug: "function-profile",
    name: "个人中心",
    nameEn: "Profile",
    description: "奶油色小猫头像特写，适合个人中心入口",
    image: "/assets/icons/function/function_profile.png",
    category: "function",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["用户头像", "个人中心", "账户入口"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "function-cart",
    slug: "function-cart",
    name: "购物车",
    nameEn: "Cart",
    description: "奶油色小猫推着购物车，适合电商购物车图标",
    image: "/assets/icons/function/function_cart.png",
    category: "function",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["购物车", "商品收藏", "结算入口"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "function-favorite",
    slug: "function-favorite",
    name: "收藏",
    nameEn: "Favorite",
    description: "奶油色小猫抱着爱心，适合收藏/喜欢功能",
    image: "/assets/icons/function/function_favorite.png",
    category: "function",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["收藏功能", "点赞按钮", "喜欢标记"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "function-share",
    slug: "function-share",
    name: "分享",
    nameEn: "Share",
    description: "奶油色小猫拿着纸飞机，适合分享功能图标",
    image: "/assets/icons/function/function_share.png",
    category: "function",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["分享按钮", "转发功能", "社交分享"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "function-download",
    slug: "function-download",
    name: "下载",
    nameEn: "Download",
    description: "奶油色小猫与纸飞机，适合下载功能图标",
    image: "/assets/icons/function/function_download.png",
    category: "function",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["下载按钮", "保存功能", "导出入口"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "function-upload",
    slug: "function-upload",
    name: "上传",
    nameEn: "Upload",
    description: "奶油色小猫与向上箭头，适合上传功能图标",
    image: "/assets/icons/function/function_upload.png",
    category: "function",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["上传按钮", "导入功能", "提交入口"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "function-edit",
    slug: "function-edit",
    name: "编辑",
    nameEn: "Edit",
    description: "奶油色小猫拿着铅笔，适合编辑功能图标",
    image: "/assets/icons/function/function_edit.png",
    category: "function",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["编辑按钮", "修改入口", "写作功能"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "function-calendar",
    slug: "function-calendar",
    name: "日历",
    nameEn: "Calendar",
    description: "奶油色小猫与日历，适合日程/日期功能图标",
    image: "/assets/icons/function/function_calendar.png",
    category: "function",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["日历入口", "日程管理", "日期选择"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },

  // ==================== 表情图标 (Emotion Icons) ====================
  {
    id: "emotion-success",
    slug: "emotion-success",
    name: "成功",
    nameEn: "Success",
    description: "奶油色小猫举起双手庆祝，适合成功状态提示",
    image: "/assets/icons/emotion/emotion_success.png",
    category: "emotion",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["成功提示", "完成状态", "庆祝动画"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "emotion-error",
    slug: "emotion-error",
    name: "错误",
    nameEn: "Error",
    description: "奶油色小猫与叉号，担忧表情，适合错误提示",
    image: "/assets/icons/emotion/emotion_error.png",
    category: "emotion",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["错误提示", "失败状态", "警告信息"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "emotion-warning",
    slug: "emotion-warning",
    name: "警告",
    nameEn: "Warning",
    description: "奶油色小猫与感叹号，警觉表情，适合警告提示",
    image: "/assets/icons/emotion/emotion_warning.png",
    category: "emotion",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["警告提示", "注意事项", "风险提醒"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "emotion-running",
    slug: "emotion-running",
    name: "奔跑",
    nameEn: "Running",
    description: "奶油色小猫奔跑姿态，适合加载/进行中状态",
    image: "/assets/icons/emotion/emotion_running.png",
    category: "emotion",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["加载动画", "进行中", "处理状态"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "emotion-happy",
    slug: "emotion-happy",
    name: "开心",
    nameEn: "Happy",
    description: "奶油色小猫眯眼微笑，非常开心的表情",
    image: "/assets/icons/emotion/emotion_happy.png",
    category: "emotion",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["正面反馈", "满意状态", "欢迎提示"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "emotion-sad",
    slug: "emotion-sad",
    name: "难过",
    nameEn: "Sad",
    description: "奶油色小猫流泪，悲伤的表情",
    image: "/assets/icons/emotion/emotion_sad.png",
    category: "emotion",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["空状态", "无结果", "遗憾提示"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "emotion-thinking",
    slug: "emotion-thinking",
    name: "思考",
    nameEn: "Thinking",
    description: "奶油色小猫手托下巴思考，适合等待/思考状态",
    image: "/assets/icons/emotion/emotion_thinking.png",
    category: "emotion",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["思考中", "处理中", "AI思考"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "emotion-sleeping",
    slug: "emotion-sleeping",
    name: "睡眠",
    nameEn: "Sleeping",
    description: "奶油色小猫安静睡觉，带有 zzz 符号",
    image: "/assets/icons/emotion/emotion_sleeping.png",
    category: "emotion",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["休眠状态", "静默模式", "暂停提示"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "emotion-surprised",
    slug: "emotion-surprised",
    name: "惊讶",
    nameEn: "Surprised",
    description: "奶油色小猫睁大眼睛，惊讶的表情",
    image: "/assets/icons/emotion/emotion_surprised.png",
    category: "emotion",
    tags: ["cute", "3d", "clay", "pastel", "cat"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["惊喜提示", "新功能", "意外状态"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },

  // ==================== 装饰素材 (Decoration Assets) ====================
  {
    id: "decoration-star",
    slug: "decoration-star",
    name: "星星",
    nameEn: "Star",
    description: "奶油色小猫抱着大星星，适合页面装饰或高亮标记",
    image: "/assets/icons/decoration/decoration_star.png",
    category: "decoration",
    tags: ["cute", "3d", "clay", "pastel", "cat", "colorful"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["页面装饰", "收藏标记", "精选标签"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "decoration-heart",
    slug: "decoration-heart",
    name: "爱心",
    nameEn: "Heart",
    description: "奶油色小猫躺在粉色爱心里，适合情感类装饰",
    image: "/assets/icons/decoration/decoration_heart.png",
    category: "decoration",
    tags: ["cute", "3d", "clay", "pastel", "cat", "colorful"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["喜欢标记", "情感装饰", "节日主题"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "decoration-cloud",
    slug: "decoration-cloud",
    name: "云朵",
    nameEn: "Cloud",
    description: "奶油色小猫趴在云朵上，适合梦幻/轻松场景",
    image: "/assets/icons/decoration/decoration_cloud.png",
    category: "decoration",
    tags: ["cute", "3d", "clay", "pastel", "cat", "minimal"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["背景装饰", "云存储", "梦境主题"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "decoration-flower",
    slug: "decoration-flower",
    name: "花朵",
    nameEn: "Flower",
    description: "奶油色小猫捧着雏菊花，适合自然/清新主题",
    image: "/assets/icons/decoration/decoration_flower.png",
    category: "decoration",
    tags: ["cute", "3d", "clay", "pastel", "cat", "colorful"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["春季主题", "自然装饰", "礼物标签"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "decoration-ribbon",
    slug: "decoration-ribbon",
    name: "蝴蝶结",
    nameEn: "Ribbon",
    description: "奶油色小猫头戴粉色蝴蝶结，适合可爱/礼品主题",
    image: "/assets/icons/decoration/decoration_ribbon.png",
    category: "decoration",
    tags: ["cute", "3d", "clay", "pastel", "cat", "colorful"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["礼品装饰", "可爱标签", "女性主题"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "decoration-balloon",
    slug: "decoration-balloon",
    name: "气球",
    nameEn: "Balloon",
    description: "奶油色小猫拿着彩色气球，适合庆祝/生日主题",
    image: "/assets/icons/decoration/decoration_balloon.png",
    category: "decoration",
    tags: ["cute", "3d", "clay", "pastel", "cat", "colorful"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["庆祝装饰", "生日主题", "活动标记"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "decoration-sparkle",
    slug: "decoration-sparkle",
    name: "闪光",
    nameEn: "Sparkle",
    description: "奶油色小猫周围环绕闪光，适合魔法/特效装饰",
    image: "/assets/icons/decoration/decoration_sparkle.png",
    category: "decoration",
    tags: ["cute", "3d", "clay", "pastel", "cat", "colorful"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["魔法效果", "新功能", "闪亮标记"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "decoration-leaf",
    slug: "decoration-leaf",
    name: "树叶",
    nameEn: "Leaf",
    description: "奶油色小猫玩弄绿色树叶，适合自然/环保主题",
    image: "/assets/icons/decoration/decoration_leaf.png",
    category: "decoration",
    tags: ["cute", "3d", "clay", "pastel", "cat", "colorful"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["自然主题", "环保标签", "秋季装饰"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
  {
    id: "decoration-crown",
    slug: "decoration-crown",
    name: "皇冠",
    nameEn: "Crown",
    description: "奶油色小猫戴着小皇冠，适合VIP/特权标记",
    image: "/assets/icons/decoration/decoration_crown.png",
    category: "decoration",
    tags: ["cute", "3d", "clay", "pastel", "cat", "colorful"],
    source: "gemini",
    size: { width: 512, height: 512 },
    useCases: ["VIP标记", "特权标签", "排行榜装饰"],
    compatibleStyles: ["soft-ui", "claymorphism"],
    createdAt: "2025-02-03",
  },
];

/**
 * Get asset by slug
 */
export function getAssetBySlug(slug: string): AssetMeta | undefined {
  return assetsMeta.find((asset) => asset.slug === slug);
}

/**
 * Get assets by category
 */
export function getAssetsByCategory(category: AssetCategory): AssetMeta[] {
  return assetsMeta.filter((asset) => asset.category === category);
}

/**
 * Get assets by tag
 */
export function getAssetsByTag(tag: AssetTag): AssetMeta[] {
  return assetsMeta.filter((asset) => asset.tags.includes(tag));
}

/**
 * Get assets compatible with a style
 */
export function getAssetsForStyle(styleSlug: string): AssetMeta[] {
  return assetsMeta.filter((asset) =>
    asset.compatibleStyles?.includes(styleSlug)
  );
}

/**
 * Search assets by name or description
 */
export function searchAssets(query: string): AssetMeta[] {
  const lowerQuery = query.toLowerCase();
  return assetsMeta.filter(
    (asset) =>
      asset.name.toLowerCase().includes(lowerQuery) ||
      asset.nameEn.toLowerCase().includes(lowerQuery) ||
      asset.description.toLowerCase().includes(lowerQuery) ||
      asset.tags.some((tag) => tag.toLowerCase().includes(lowerQuery))
  );
}
