/**
 * Asset metadata system
 *
 * Manages cute cartoon assets generated by AI tools (Banana Nano, Midjourney, etc.)
 * Supports categorization, tagging, and integration into UI components
 */

export type AssetCategory =
  | "button"
  | "decoration"
  | "character"
  | "background"
  | "icon"
  | "badge"
  | "illustration";

export type AssetTag =
  | "cute"
  | "playful"
  | "minimal"
  | "colorful"
  | "monochrome"
  | "3d"
  | "flat"
  | "hand-drawn"
  | "geometric"
  | "organic";

export interface AssetMeta {
  id: string;
  slug: string;
  name: string;
  nameEn: string;
  description: string;
  image: string;
  thumbnail?: string;
  category: AssetCategory;
  tags: AssetTag[];
  source?: "banana-nano" | "midjourney" | "dalle" | "custom";
  colors?: string[];
  size?: {
    width: number;
    height: number;
  };
  useCases?: string[];
  compatibleStyles?: string[];
  createdAt?: string;
}

/**
 * Asset registry - all available assets
 * Start with placeholder entries, will be populated with actual assets
 */
export const assetsMeta: AssetMeta[] = [
  {
    id: "banana-nano-1",
    slug: "banana-nano-button-1",
    name: "香蕉按钮",
    nameEn: "Banana Button",
    description: "可爱的香蕉卡通角色，适合作为按钮装饰或交互元素",
    image: "/assets/banana-nano-button-1.png",
    thumbnail: "/assets/thumbnails/banana-nano-button-1.png",
    category: "button",
    tags: ["cute", "playful", "colorful"],
    source: "banana-nano",
    colors: ["#FFD700", "#FFA500", "#FFFFFF"],
    size: { width: 200, height: 200 },
    useCases: ["按钮装饰", "交互反馈", "加载动画"],
    compatibleStyles: ["neo-brutalist-playful", "soft-ui"],
    createdAt: "2025-02-03",
  },
  {
    id: "cute-character-1",
    slug: "cute-character-smile",
    name: "微笑角色",
    nameEn: "Smiling Character",
    description: "友好的卡通角色，带有温暖的微笑表情",
    image: "/assets/cute-character-smile.png",
    thumbnail: "/assets/thumbnails/cute-character-smile.png",
    category: "character",
    tags: ["cute", "playful", "hand-drawn"],
    source: "custom",
    colors: ["#FF69B4", "#FFB6C1", "#FFFFFF"],
    size: { width: 300, height: 300 },
    useCases: ["欢迎页面", "成功提示", "品牌代言"],
    compatibleStyles: ["soft-ui", "neo-brutalist-playful"],
    createdAt: "2025-02-03",
  },
  {
    id: "decoration-flower",
    slug: "decoration-flower-bloom",
    name: "花朵装饰",
    nameEn: "Flower Decoration",
    description: "彩色花朵装饰元素，适合页面点缀",
    image: "/assets/decoration-flower-bloom.png",
    thumbnail: "/assets/thumbnails/decoration-flower-bloom.png",
    category: "decoration",
    tags: ["colorful", "organic", "flat"],
    source: "custom",
    colors: ["#FF1493", "#FFD700", "#00CED1"],
    size: { width: 150, height: 150 },
    useCases: ["页面装饰", "分隔符", "背景元素"],
    compatibleStyles: ["soft-ui", "minimalist-flat"],
    createdAt: "2025-02-03",
  },
  {
    id: "badge-star",
    slug: "badge-star-shine",
    name: "闪耀徽章",
    nameEn: "Shining Badge",
    description: "闪耀的星形徽章，用于标记特殊内容",
    image: "/assets/badge-star-shine.png",
    thumbnail: "/assets/thumbnails/badge-star-shine.png",
    category: "badge",
    tags: ["colorful", "geometric", "3d"],
    source: "custom",
    colors: ["#FFD700", "#FFA500", "#FFFFFF"],
    size: { width: 100, height: 100 },
    useCases: ["新品标签", "推荐标记", "成就徽章"],
    compatibleStyles: ["neo-brutalist-playful", "soft-ui"],
    createdAt: "2025-02-03",
  },
];

/**
 * Get asset by slug
 */
export function getAssetBySlug(slug: string): AssetMeta | undefined {
  return assetsMeta.find((asset) => asset.slug === slug);
}

/**
 * Get assets by category
 */
export function getAssetsByCategory(category: AssetCategory): AssetMeta[] {
  return assetsMeta.filter((asset) => asset.category === category);
}

/**
 * Get assets by tag
 */
export function getAssetsByTag(tag: AssetTag): AssetMeta[] {
  return assetsMeta.filter((asset) => asset.tags.includes(tag));
}

/**
 * Get assets compatible with a style
 */
export function getAssetsForStyle(styleSlug: string): AssetMeta[] {
  return assetsMeta.filter((asset) =>
    asset.compatibleStyles?.includes(styleSlug)
  );
}

/**
 * Search assets by name or description
 */
export function searchAssets(query: string): AssetMeta[] {
  const lowerQuery = query.toLowerCase();
  return assetsMeta.filter(
    (asset) =>
      asset.name.toLowerCase().includes(lowerQuery) ||
      asset.nameEn.toLowerCase().includes(lowerQuery) ||
      asset.description.toLowerCase().includes(lowerQuery) ||
      asset.tags.some((tag) => tag.toLowerCase().includes(lowerQuery))
  );
}
